### ISSUE TITLE
It doesn't work if not enable `iterm2 Tmux integration` 

### ISSUE THREAD

**Issue by cynial** [trzsz/trzsz#1]
It will open transfer dialog looply if not enable `iterm2 Tmux integration`

**Comment by lonnywong** [comment]
Yes, It is not working with tmux non control mode.

I'm working on it.

**Comment by lonnywong** [comment]
[v0.1.3](https://github.com/trzsz/trzsz/releases/tag/v0.1.3) should works with tmux without [iTerm2 tmux Integration](https://iterm2.com/documentation-tmux-integration.html).

Try this:
* server side
```
python3 -m pip install --upgrade --force-reinstall trzsz-libs trzsz-svr
```
* client side
```
python3 -m pip install --upgrade --force-reinstall trzsz-libs trzsz-iterm2
```

**Comment by ruanima** [comment]
@lonnywong  good job 👍 👍

**Comment by lonnywong** [comment]
> It will open transfer dialog looply if not enable `iterm2 Tmux integration`

Is https://github.com/trzsz/trzsz/issues/1#issuecomment-996520939 working? 

I'm going to close the issue if it's woking.

**Comment by lonnywong** [comment]
While I am testing v0.1.4, it fails sometimes.
Working on it. Should be fixed at v0.1.4 .

**Comment by MF-ReStart** [comment]
你好，请问现在还有问题吗，能够进行正常使用了吗？

**Comment by lonnywong** [comment]
> 你好，请问现在还有问题吗，能够进行正常使用了吗？

现在可以正常使用的，不用 tmux ，或者只用 tmux -CC 控制模式的，目前是没有发现问题的。

tmux 普通模式偶尔会失败，在 v0.1.4 应该就能解决，代码已经写完了，在测试验证，预计今晚或明天就会发布。

**Comment by MF-ReStart** [comment]
你好，我之前就遇到过tmux不能使用rz sz的问题，后来我放弃了tmux，现在我看到了希望，非常谢谢你，我会一直关注你的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "trzsz/trzsz"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月23日(星期四) 下午2:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [trzsz/trzsz] It doesn't work if not enable `iterm2 Tmux integration`  (Issue #1)





  
你好，请问现在还有问题吗，能够进行正常使用了吗？
  
现在可以正常使用的，不用 tmux ，或者只用 tmux -CC 控制模式的，目前是没有发现问题的。
 
tmux 普通模式偶尔会失败，在 v0.1.4 应该就能解决，代码已经写完了，在测试验证，预计今晚或明天就会发布。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lonnywong** [comment]
fully support tmux at [v0.1.4](https://github.com/trzsz/trzsz/releases/tag/v0.1.4)
