### ISSUE TITLE
能否支持Ubuntu默认终端?

### ISSUE THREAD

**Issue by pengatgstdev** [trzsz/trzsz#10]

**Comment by lonnywong** [comment]
1. 因为 Ubuntu 默认终端不支持类似 [iTerm2 Coprocesses](https://iterm2.com/documentation-coprocesses.html) 的扩展，无法通过扩展来实现客户端。
2. 修改 Ubuntu 的默认终端，但那就不再是默认终端了。
3. 找一个开源的 ssh 终端来修改，暂时没发现有易于扩展的 Linux 开源终端。
4. 暂时只找到 SecureCRT 是支持 ZMODEM 且可以运行在 Linux 上的，可惜 SecureCRT 不是开源的。

**Comment by pengatgstdev** [comment]
感谢回答

**Comment by lonnywong** [comment]
找到一个 ssh 客户端 [electerm](https://github.com/electerm/electerm)，可以试试看能不能搞。

**Comment by pengatgstdev** [comment]
谢谢, 我在想换个思路, 是否可行呢?  比如不弹出文件选择弹框(改为手动输入文件地址), 比如: 往远程服务器传输本机文件/d/test.php到目录/mnt/
trz   /d/test.php   /mnt/

**Comment by pengatgstdev** [comment]
这样手动输入文件地址  "trz /d/test.php /mnt/", 就避开了iTerm2的触发设置;

**Comment by lonnywong** [comment]
重要的是远程服务器的输出要让 trzsz 来接收，trzsz 的输出要发送给远程服务器。这是 [iTerm2 Coprocesses](https://iterm2.com/documentation-coprocesses.html) 提供的能力。

**Comment by pengatgstdev** [comment]
谢谢,  可以在官网说明文档中,详细介绍下trzsz文件传输的实现机制和设计思路吗?

**Comment by lonnywong** [comment]
> 谢谢, 可以在官网说明文档中,详细介绍下trzsz文件传输的实现机制和设计思路吗?

其实不复杂：
1. 服务端输出一串特定的字符串。
2. iTerm2配置触发器，遇到这特定的字符串时就拉起客户端。然后，iTerm2会将服务端的输出转成客户端的输入，将客户端的输出转成服务端的输入。这样，客户端就可以与服务端进行通讯了。
3. 上传时，客户端选择要发送的文件，将文件个数、文件名、文件内容发送给服务端，服务端收到后写入文件。
4. 下载时，服务端指定要下载的文件列表，客户端选择要保存的位置，服务端将文件个数、文件名、文件内容发送给客户端，客户端收到后写入文件。

**Comment by pengatgstdev** [comment]
".....iTerm2会将服务端的输出转成客户端的输入，将客户端的输出转成服务端的输入。"  这句能举例讲下吗?

**Comment by lonnywong** [comment]
> ".....iTerm2会将服务端的输出转成客户端的输入，将客户端的输出转成服务端的输入。" 这句能举例讲下吗?

就是 [iTerm2 Coprocesses](https://iterm2.com/documentation-coprocesses.html) 提供的能力，你点这个链接去看就是了，不过是英文的。

**Comment by pengatgstdev** [comment]
好的谢谢

**Comment by ruanima** [comment]
> 1. 因为 Ubuntu 默认终端不支持类似 [iTerm2 Coprocesses](https://iterm2.com/documentation-coprocesses.html) 的扩展，无法通过扩展来实现客户端。
> 2. 修改 Ubuntu 的默认终端，但那就不再是默认终端了。
> 3. 找一个开源的 ssh 终端来修改，暂时没发现有易于扩展的 Linux 开源终端。
> 4. 暂时只找到 SecureCRT 是支持 ZMODEM 且可以运行在 Linux 上的，可惜 SecureCRT 不是开源的。

可以看看 https://github.com/Eugeny/tabby

**Comment by pengatgstdev** [comment]
@ruanima 这个tabby说支持"在 SSH 会话中通过 Zmodem 进行直接文件传输", 但是测试rzsz好像不行

**Comment by ruanima** [comment]
@pengatgstdev 

![image](https://user-images.githubusercontent.com/14031394/157389338-f324f952-56d5-4863-b0dd-a721d9729d03.png)

**Comment by lonnywong** [comment]
> > 1. 因为 Ubuntu 默认终端不支持类似 [iTerm2 Coprocesses](https://iterm2.com/documentation-coprocesses.html) 的扩展，无法通过扩展来实现客户端。
> > 2. 修改 Ubuntu 的默认终端，但那就不再是默认终端了。
> > 3. 找一个开源的 ssh 终端来修改，暂时没发现有易于扩展的 Linux 开源终端。
> > 4. 暂时只找到 SecureCRT 是支持 ZMODEM 且可以运行在 Linux 上的，可惜 SecureCRT 不是开源的。
> 
> 可以看看 https://github.com/Eugeny/tabby

你是建议将 trzsz 集成到 tabby ？如果作者愿意的话，是可行的。
我用 `js` 写了个 trzsz 的客户端组件，已经写好了，在测试中，还没发布。

**Comment by ruanima** [comment]
> 3. 找一个开源的 ssh 终端来修改，暂时没发现有易于扩展的 Linux 开源终端。

@lonnywong  只是回答前面的这个问题；看了下js的客户端组件，感觉非常好  o(￣▽￣)ｄ

**Comment by pengatgstdev** [comment]
> @pengatgstdev
> 
> ![image](https://user-images.githubusercontent.com/14031394/157389338-f324f952-56d5-4863-b0dd-a721d9729d03.png)
昨天晚上在Ubuntu上测试了下tabby, rzsz确实可以用;

**Comment by engcn** [comment]
> > > 1. 因为 Ubuntu 默认终端不支持类似 [iTerm2 Coprocesses](https://iterm2.com/documentation-coprocesses.html) 的扩展，无法通过扩展来实现客户端。
> > > 2. 修改 Ubuntu 的默认终端，但那就不再是默认终端了。
> > > 3. 找一个开源的 ssh 终端来修改，暂时没发现有易于扩展的 Linux 开源终端。
> > > 4. 暂时只找到 SecureCRT 是支持 ZMODEM 且可以运行在 Linux 上的，可惜 SecureCRT 不是开源的。
> > 
> > 
> > 可以看看 https://github.com/Eugeny/tabby
> 
> 你是建议将 trzsz 集成到 tabby ？如果作者愿意的话，是可行的。 我用 `js` 写了个 trzsz 的客户端组件，已经写好了，在测试中，还没发布。

什么时候发布啊? 在线等挺急的...

**Comment by lonnywong** [comment]
> 什么时候发布啊? 在线等挺急的...

组件在写单测，还有文档，快的话是周末会发布，但不一定搞的完。

[electerm](https://github.com/electerm/electerm) 是在测试中了，还没提 PR，也得作者愿意合入，还要等他发布才行。

[tabby](https://github.com/Eugeny/tabby) 我还没空去仔细看，也是 electron 的，但是没用 xterm.js，还不知怎么对接。

**Comment by engcn** [comment]
> > 什么时候发布啊? 在线等挺急的...
> 
> 组件在写单测，还有文档，快的话是周末会发布，但不一定搞的完。
> 
> [electerm](https://github.com/electerm/electerm) 是在测试中了，还没提 PR，也得作者愿意合入，还要等他发布才行。
> 
> [tabby](https://github.com/Eugeny/tabby) 我还没空去仔细看，也是 electron 的，但是没用 xterm.js，还不知怎么对接。

ok, 谢谢大神

**Comment by lonnywong** [comment]
`js` 组件已发布 `v0.3.0`，https://github.com/trzsz/trzsz.js

客户端已搞完，服务端还是用 `python` 版本 [trzsz](https://github.com/trzsz/trzsz)，有空再搞 `js` 版的服务端。

`electerm` 已提 PR：https://github.com/electerm/electerm/pull/2388

**Comment by lonnywong** [comment]
@pengatgstdev @ruanima @engcn 

[electerm](https://github.com/electerm/electerm) 发布了 [v1.19.0](https://github.com/electerm/electerm/releases/tag/v1.19.0)，我在 Mac、Win 和 Ubuntu 都测试了下，可以正常用。

*Win 下通过 PowerShell 登录到 wsl 中除外，吓我一跳，估计是 PowerShell 在搞事。*

**Comment by engcn** [comment]
> @pengatgstdev @ruanima @engcn
> 
> [electerm](https://github.com/electerm/electerm) 发布了 [v1.19.0](https://github.com/electerm/electerm/releases/tag/v1.19.0)，我在 Mac、Win 和 Ubuntu 都测试了下，可以正常用。
> 
> _Win 下通过 PowerShell 登录到 wsl 中除外，吓我一跳，估计是 PowerShell 在搞事。_

@lonnywong 谢谢，刚才在Ubuntu下测试了下，太好使啦;

**Comment by lonnywong** [comment]
@engcn 什么样的表现？我试了下是可以在 tmux 中用的。

要注意的是：只支持先 ssh 到远程服务器，在远程服务器上运行 tmux ；不支持先本地运行 tmux ，然后 ssh 到远程服务器上。

对于本地先运行 tmux 的，目前只支持 iTerm2 的 tmux -CC 的用法，在 https://github.com/trzsz/trzsz/issues/9 上说的也这个问题。

**Comment by engcn** [comment]
我是先ssh登录到远程服务器，再在远程服务器上运行 tmux; 报如下:
[root@teng mnt]# trz
::TRZSZ:TRANSFER:R:0.3.1:2451550917461
然后就没反应了,只能Ctrl-C退出了

我的客户端所在系统环境是Ubuntu20.04.3, 服务端是CentOS7, electerm版本是
https://github.com/electerm/electerm/releases/download/v1.19.0/electerm-1.19.0-linux-x64.tar.gz

**Comment by lonnywong** [comment]
> ::TRZSZ:TRANSFER:R:0.3.1:2451550917461

没响应，除非前几次 js 启动慢，一般来说就是匹配这个字符串时没匹配上，不知道用户运行了 trz / tsz 。

屏幕不会小到这个字符串要换行吧？

这么短的字符串不会被拆成 2 个 tcp 包吧（这里实现是偷懒了，需要一次性返回完整的字符串才能匹配上。）

返回的数据类型不对？不会吧，不用 tmux 时可以，按理说数据类型是没问题的。

tmux 一般是在前后加入一些数据，但这并不会影响匹配，除非显示换行了，tmux 加入的数据就会影响匹配，导致不知道用户运行了 trzsz。

**Comment by engcn** [comment]
屏幕不小,  晚上回去我再试试, 谢谢啦

**Comment by engcn** [comment]
哦哦,谢谢回答

**Comment by lonnywong** [comment]
> 我是先ssh登录到远程服务器，再在远程服务器上运行 tmux; 报如下: [root@teng mnt]# trz ::TRZSZ:TRANSFER:R:0.3.1:2451550917461 然后就没反应了,只能Ctrl-C退出了
> 
> 我的客户端所在系统环境是Ubuntu20.04.3, 服务端是CentOS7, electerm版本是 https://github.com/electerm/electerm/releases/download/v1.19.0/electerm-1.19.0-linux-x64.tar.gz

@engcn 当 tmux 重刷屏幕输出时，带有 `:` 时确实会触发一个 bug ，已修复。[electerm](https://github.com/electerm/electerm) 已提 PR。

**Comment by lonnywong** [comment]
@ruanima @pengatgstdev @engcn 

现在 [tabby](https://github.com/Eugeny/tabby) 也支持 trzsz 了，安装一个插件即可：https://github.com/trzsz/tabby-trzsz

**Comment by engcn** [comment]
刚才测试tabby安装trzsz插件后，很好用； 如果可能，可以给Ubuntu的默认终端gnome-terminal提pr支持trzsz

**Comment by ruanima** [comment]
@engcn  gnome-terminal 不支持插件系统吧，而且这种系统终端也不会轻易支持外部插件

**Comment by lonnywong** [comment]
> 刚才测试tabby安装trzsz插件后，很好用； 如果可能，可以给Ubuntu的默认终端gnome-terminal提pr支持trzsz

如果你是喜欢 Ubuntu 默认终端的颜色，那第三方终端都可以改的，可以长的很像 Ubuntu 默认终端。

默认终端不好改，除非自己拉一个分支出来，自己改，自己用。如果想发布到正式版中，那太难了。

**Comment by engcn** [comment]
> > 刚才又在tmux中测试了下，第一次失败，之后trz都成功上传；
> > 上传成功之后有点小问题，进度条留在那里了。
> > ![图片](https://user-images.githubusercontent.com/26758766/158204479-ef129792-33c6-4a9b-ad06-bf220caa0df3.png)
> 
> `js` 的问题就是启动慢，一个函数需要多运行几次，才会被编译成机器码，之后就快了。
> 
> 残留的进度条只是在客户端显示，其实服务端是没有输出进度条的，只要服务端的输出有刷新，那个进度条就会自动消失。同一个分屏内的自动消失了，另一个分屏的要让他刷新不好搞。

tmux中多个pane中进度条显示问题, 如果只保留百分比数字进度, 不要进度条, 是不是好搞点啊?

**Comment by lonnywong** [comment]
> tmux中多个pane中进度条显示问题, 如果只保留百分比数字进度, 不要进度条, 是不是好搞点啊?

进度条的显示内容会根据宽度自动调整的，这个已经实现。

只在当前 pane 中显示进度条估计也是可以实现的。一是在服务端算出当前 pane 的宽度，这个好实现。二是要算出当前 pane 距离左边的 offset，这个要研究一下 tmux 有没有现成的命令可以获取。

**Comment by lonnywong** [comment]
> 
> tmux中多个pane中进度条显示问题, 如果只保留百分比数字进度, 不要进度条, 是不是好搞点啊?

已支持，服务端升级到 1.0.0 版本，tabby 插件升级到 0.1.3 即可。

**Comment by lonnywong** [comment]
@pengatgstdev @ruanima 用 https://github.com/trzsz/trzsz-go 这个可以支持 ubuntu 默认终端，刚实现基本功能（ 未完全测试），可以先试用下，有问题可以提 issue 。

**Comment by engcn** [comment]
太棒了，非常感谢你。“rzsz不支持 ubuntu 默认终端”这个问题困扰我好几年了, 如梗在喉；我刚在Ubuntu上测试，只有一点体验上的小问题，一会提在trzsz-go里吧。
