### ISSUE TITLE
Documentation bug: new homebrew path location

### ISSUE THREAD

**Issue by tidux** [trzsz/trzsz#11]
On Monterey on Apple Silicon, the files installed by Homebrew are in /opt/homebrew instead of /usr/local.  This means the trzsz-iterm2 binary is in /opt/homebrew/bin/trzsz-iterm2.  Please update documentation and screenshots accordingly.

**Comment by lonnywong** [comment]
Thanks. I'm aware of the issue, but haven't found a way to make the documentation clear yet. Any suggestion?
In addition, I'm going to support a text progress bar, which switch by `-p` option.
One of the valid configuration may be `/opt/homebrew/bin/trzsz-iterm2 -p text \1`

**Comment by lonnywong** [comment]
The documentation has been updated.
