### ISSUE TITLE
下载文件存放目录支持配置，避免每次都选择路径

### ISSUE THREAD

**Issue by ruanima** [trzsz/trzsz#15]

**Comment by pengatgstdev** [comment]
上传文件选择目录也是, 支持配置或者能记住上次选择的目录更好

**Comment by ruanima** [comment]
@lonnywong  用的iterm2, 我去配参数了 👋

**Comment by lonnywong** [comment]
> 上传文件选择目录也是, 支持配置或者能记住上次选择的目录更好

这个系统会默认记住的吧？我在  mac 上用是会的。

**Comment by pengatgstdev** [comment]
Ubuntu上tabby上传不会的

**Comment by lonnywong** [comment]
> @lonnywong 用的iterm2, 我去配参数了 👋

要周末才有空写代码哈~ 等下个版本发布（可能是下周末，快就本周末）

**Comment by pengatgstdev** [comment]
ok,谢谢

**Comment by ruanima** [comment]
> > @lonnywong 用的iterm2, 我去配参数了 👋
> 
> 要周末才有空写代码哈~ 等下个版本发布（可能是下周末，快就本周末）

我还以为本来就支持这个参数，还纳闷为啥文档里没有 😂

**Comment by lonnywong** [comment]
> @lonnywong 用的iterm2, 我去配参数了 👋

已发布，用 iTerm2 的话，将服务端和客户端都升级到 1.0 版本，就可以配参数了。

**Comment by lonnywong** [comment]
> 上传文件选择目录也是, 支持配置或者能记住上次选择的目录更好

tabby 插件已支持，更新到 0.2.0 版本（已发布，可能要等几个小时才会看到更新）。

1. 在设置里填入上传目录，选择上传文件时就会默认打开到那个目录。
2. 在设置里填入下载目录，就不会弹出对话框了，直接下载文件到那里。

**Comment by lonnywong** [comment]
为 electerm 提了个 issue：https://github.com/electerm/electerm/issues/2407
