### ISSUE TITLE
Does not support subshells.

### ISSUE THREAD

**Issue by jlane67** [trzsz/trzsz#16]
Works: `$ tsz foo.tar.gz`

Does not work: `$ for i in {foo,bar,baz}; do tsz $i.tar.gz; done`

I'm not sure whether this is intended behavior or not.

**Comment by lonnywong** [comment]
> Works: `$ tsz foo.tar.gz`
> 
> Does not work: `$ for i in {foo,bar,baz}; do tsz $i.tar.gz; done`
> 
> I'm not sure whether this is intended behavior or not.

You should do `tsz *.tar.gz` or `tsz foo.tar.gz bar.tar.gz baz.tar.gz` instead.
