### ISSUE TITLE
安装后提示升级iterm2，但是iterm2已经是最新版

### ISSUE THREAD

**Issue by BoWang816** [trzsz/trzsz#17]
<img width="528" alt="image" src="https://user-images.githubusercontent.com/26587649/165923837-a723eac9-c518-4ef2-9aba-2d30ffa86775.png">

**Comment by BoWang816** [comment]
嗯嗯，看了下是的，目前还是3.4的版本，去掉后就可以了，感谢

**Comment by Godsing** [comment]
我目前使用的是 3.5.0beta5 版本，但依然提示我更新耶？去掉 `-p text` 就好了。

**Comment by Godsing** [comment]
> > 我目前使用的是 3.5.0beta5 版本，但依然提示我更新耶？去掉 `-p text` 就好了。
> 
> iTerm2 3.5.0beta5 是 Built on March 10, 2022 这个日期打包的，是我搞错了。
> 
> 至少需要 Build 3.5.20220327-nightly 以后的，建议是 Build 3.5.20220503-nightly 以后的。

刚刚试了最新版的 Build 3.5.20220510-nightly，确实可以。感谢大佬！比心 :heart:
