### ISSUE TITLE
不支持 xshell

### ISSUE THREAD

**Issue by snsnsjsn** [trzsz/trzsz#18]
不支持 xshell

**Comment by engcn** [comment]
xshell直接用lrzsz就可以了

**Comment by lonnywong** [comment]
> 不支持 xshell

@snsnsjsn 在 xshell 中开一个本地的 bash ，或者 powershell ，然后使用 https://github.com/trzsz/trzsz-go 试试：
```
trzsz ssh yourname@x.x.x.x
```

&nbsp;
&nbsp;

> xshell直接用lrzsz就可以了

@engcn lrzsz 最大的问题是不支持 tmux 。

**Comment by snsnsjsn** [comment]
> xshell直接用lrzsz就可以了

lrzsz 不支持 tmux，我才下载 trzsz，结果 xshell和 trzsz又不能用？

**Comment by snsnsjsn** [comment]
> @snsnsjsn 在 xshell 中开一个本地的 bash ，或者 powershell ，然后使用 https://github.com/trzsz/trzsz-go 试试：

这个太麻烦哈，我直接下载了个 electerm，但是 这货很多快捷键不熟悉，而且占用内存很大。，

还是喜欢 xshell，xshell支持 zmodem文件传输模式，
为啥 不能使用  trzsz？
弹不出互动的文件选择框。

**Comment by lonnywong** [comment]
> 还是喜欢 xshell，xshell支持 zmodem文件传输模式， 为啥 不能使用 trzsz？ 弹不出互动的文件选择框。

因为 xshell 不是开源的，并且没有适合的扩展接口。

也可以试试 tabby 。

**Comment by lonnywong** [comment]
因为 xshell 不是开源的，也没有接口可以对接，所以没办法直接支持。

下面的办法可以使用：

1、下载 [https://github.com/trzsz/trzsz-go](https://github.com/trzsz/trzsz-go) windows 版本，假设将 `trzsz.exe` 解压放到 `C:\trzsz.exe` 
2、`xshell` 升级到 `7` 以上的版本
3、打开一个 `本地 shell`
4、输入 `powershell` 回车
5、使用 `C:\trzsz.exe ssh user@x.x.x.x` 登录远程服务器
6、在服务器上安装 `trz` 和 `tsz` 即可上传和下载
7、如果使用 `C:\trzsz.exe -d ssh user@x.x.x.x` 登录远程服务器 ( 即多加一个 `-d` 选项 )，那么只要在服务器上将 `trz` 放到某个 `PATH` 路径下，即可拖文件就自动上传。

**Comment by snsnsjsn** [comment]
好的，我还是用回 lrzsz， 在 暂时离开 tmux 后直接在xhsell里面操作

**Comment by liudonghua123** [comment]
> 我还是用回 lrzsz， 在 暂时离开 tmux 后直接在xhsell里面操作

可以借鉴 lrzsz 的开源实现，如果可以支持xshell，那就太方便了

**Comment by lonnywong** [comment]
> 
> 可以借鉴 lrzsz 的开源实现，如果可以支持xshell，那就太方便了

trzsz 就是借鉴 lrzsz 实现的。不支持 xshell 的原因是 xshell 不是开源的，想要 xshell 支持得找 xshell 的公司。

**Comment by liudonghua123** [comment]
嗯，我的理解是 lrzsz 是开源的并且支持xshell，可以参考一下他这一块代码是如何实现的？

**Comment by liudonghua123** [comment]
嗯嗯，明白了，弱弱的问一下：trzsz 可以伪装成 lrzxz 么（就是在linux上与lrzsz是相同的行为）

**Comment by liudonghua123** [comment]
嗯嗯，完全明白了，谢谢~ 😄

**Comment by lonnywong** [comment]
如果哪天 trzsz 很流行了，说不定 xshell 公司会主动支持呢，或者像 iTerm2 那样开放接口也是可以的。我也期待那一天。

**Comment by liudonghua123** [comment]
嗯，除了 xshell 不支持外，其他类似的例如 [SecureCRT](https://www.vandyke.com/products/securecrt
)， [PuTTY](https://putty.org) 支持吗？

**Comment by lonnywong** [comment]
> 嗯，除了 xshell 不支持外，其他类似的例如 [SecureCRT](https://www.vandyke.com/products/securecrt)， [PuTTY](https://putty.org) 支持吗？

要看有没有本地 shell，如果有本地 shell，例如 Windows Terminal，是可以使用 https://github.com/trzsz/trzsz-go 的。

只要在 ssh 登录到选程服务器时，在前面加上 trzsz，如 `trzsz ssh xxx@x.x.x.x` 登录服务器，就可以用 trz / tsz 命令上传和下载了。

**Comment by lonnywong** [comment]
可以试试 https://github.com/trzsz/trzsz-ssh
在 xshell 中打开一个本地 shell，然后用 tssh 登录，就可以用 trz / tsz 上传和下载了。

**Comment by xiaochunlee** [comment]
我这边测试了secureCRT 和 MobaXterm，都没有窗口弹出，看来还不支持。
