### ISSUE TITLE
err in python3.9

### ISSUE THREAD

**Issue by sunsky303** [trzsz/trzsz#19]
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/70417827/177022757-b394f03a-67eb-4fcb-af09-3361daf9ccaa.png">

<img width="260" alt="image" src="https://user-images.githubusercontent.com/70417827/177022790-0bd46923-8550-407d-8644-ab48370e263e.png">

**Comment by lonnywong** [comment]
感谢反馈。我试了  iTerm2 的 `3.4.15` 和 `3.4.16` 这两个版本，没能复现问题。

执行以下命令，看看 iTerm2 的 Python API 是什么版本？
```
cat /usr/local/lib/python3.9/site-packages/iterm2/_version.py
```

另外，iTerm2 发布了 `3.4.16` ，更新还没有提示，可以直接从官网下载：https://iterm2.com/downloads.html

**Comment by lonnywong** [comment]
在两个同事的 Mac 上试了，分别是 Intel 和 Apple 的芯片，iTerm2 都是 `3.4.15` 版本的，都没能复现问题。
@sunsky303 看到的话，多提供一些信息？

**Comment by liutianping0326** [comment]
@lonnywong 
我是Apple芯片，也出现了这个报错
<img width="1259" alt="image" src="https://user-images.githubusercontent.com/40854706/204091049-e23c0bb0-0fe0-4072-985f-750307d7f6b8.png">

**Comment by lonnywong** [comment]
@liutianping0326 执行 `python3 -c 'import iterm2; print(iterm2)'` 看看？

我在 M1 上执行会是正常的输出：
```
<module 'iterm2' from '/opt/homebrew/lib/python3.9/site-packages/iterm2/__init__.py'>
```

**Comment by lonnywong** [comment]
或者试试用 homebrew 安装试试：
```
python3 -m pip uninstall trzsz-libs trzsz-iterm2
brew update
brew install trzsz
```

**Comment by liutianping0326** [comment]
@lonnywong 
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/40854706/204093061-47bbc604-deb2-4b2e-b322-7f7ac65d51ae.png">

明天我再试试brew安装

**Comment by liutianping0326** [comment]
@lonnywong 
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/40854706/204093120-b6df1772-3506-4c63-9c3d-37c505d74b33.png">
明天我再试试brew安装

**Comment by lonnywong** [comment]
@liutianping0326 用 brew 安装是否可以？

**Comment by lonnywong** [comment]
@liutianping0326 感谢反馈。

这个问题可能是 python protobuf 版本不兼容。
用 brew 安装时，实际是一个 python venv，不会存在兼容问题。

这 issue 我先关闭了。
