### ISSUE TITLE
About  common soft-chain for Mac Client

### ISSUE THREAD

**Issue by garywu520** [trzsz/trzsz#2]
Mac Client needs to make a soft chain to work, otherwise it will be prompted: /usr/local/bin/trzsz-Iterm2  not found.

<br>

Mac Client side
```
sudo python3 -m pip install --upgrade trzsz-libs trzsz-iterm2
ln -sv /Library/Frameworks/Python.framework/Versions/3.9/bin/trzsz-iterm2 /usr/local/bin/
ls -lh /usr/local/bin/trzsz-iterm2
brew install ncruces/tap/zenity
```

Good Job, thanks!

**Comment by lonnywong** [comment]
> Mac Client needs to make a soft chain to work, otherwise it will be prompted: /usr/local/bin/trzsz-Iterm2 not found.
> 
> 
> Mac Client side
> 
> ```
> sudo python3 -m pip install --upgrade trzsz-libs trzsz-iterm2
> ln -sv /Library/Frameworks/Python.framework/Versions/3.9/bin/trzsz-iterm2 /usr/local/bin/
> ls -lh /usr/local/bin/trzsz-iterm2
> brew install ncruces/tap/zenity
> ```
> 
> Good Job, thanks!

@garywu520 Thanks for your feedback.

The python environment is a little different. I will update the installation guidelines.

**Comment by garywu520** [comment]
Thanks for the reply. In addition, after my test, the server can work normally when using python2 or python3 to install trzsz-svr. The document can also be appropriately revised to avoid confusion for users. For example: I don't want to deliberately install a python3 in order to use trzsz.

In addition, the point that confuses me is that the download speed is slower than that of lrzsz. Can you explain why? Thanks!

**Comment by lonnywong** [comment]
> Thanks for the reply. In addition, after my test, the server can work normally when using python2 or python3 to install trzsz-svr. The document can also be appropriately revised to avoid confusion for users. For example: I don't want to deliberately install a python3 in order to use trzsz.
> 
> In addition, the point that confuses me is that the download speed is slower than that of lrzsz. Can you explain why? Thanks!

Yep, trzsz supports python2. I will update guidelines later.

In order to be compatible with tmux, trzsz is using base64, the speed should be 75% of lrzsz.

But, downloading files may support binary mode, which will catch up the speed of lrzsz.

Uploading files is much harder to support binary mode, Since have to avoid tmux control characters.

**Comment by garywu520** [comment]
ok,thanks.
