### ISSUE TITLE
Not supported in Konsole

### ISSUE THREAD

**Issue by xubooo2** [trzsz/trzsz#20]
trzsz seems not supported in Konsole (Debian tesing, KDE).
anybond konw how to have the same experience on Linux just like Xshell on win10? 
I desire quickly download and upload file between remote server and local PC only by terminal.

**Comment by lonnywong** [comment]
> trzsz seems not supported in Konsole (Debian tesing, KDE).

Could you share any error message ?

You can also try https://github.com/trzsz/trzsz-go .

**Comment by lonnywong** [comment]
Another option: https://github.com/trzsz/trzsz-ssh
