### ISSUE TITLE
安利支持，putty和secureCRT

### ISSUE THREAD

**Issue by wangshankun** [trzsz/trzsz#21]
这两个终端在Windows开发很常见

**Comment by lonnywong** [comment]
试试 https://github.com/trzsz/trzsz-go 能不能用？

**Comment by wangshankun** [comment]
> 试试 https://github.com/trzsz/trzsz-go 能不能用？
> 
> SecureCRT 新建 Session 时选择 `Local Shell`，然后选择 `cmd` 或 `PowerShell` 的路径。 在里面执行 `trzsz ssh x.x.x.x` 登录到远程服务器，就可以使用 `trz` 上传，`tsz` 下载了。

是可以的，不知道为什么速度那么慢？只是本地的虚拟机
![image](https://user-images.githubusercontent.com/3970271/181267449-4954f526-e1be-4a10-b9ff-e0e37553c3a1.png)

**Comment by lonnywong** [comment]
> 是可以的，不知道为什么速度那么慢？只是本地的虚拟机 ![image](https://user-images.githubusercontent.com/3970271/181267449-4954f526-e1be-4a10-b9ff-e0e37553c3a1.png)
> 
> Receive data timeout 后就崩了

是很慢，我研究了很久都没解决，估计是 Windows 的 ConPTY 限速了还是什么原因。下载速度还算可以，有 2M 以上。我提了个 issue https://github.com/microsoft/terminal/issues/13594 ，希望能解决。

会自动选择缓冲区大小的，按理说不应该触发 Receive data timeout 的，可能是文件前半部分和后半部分压缩率差异大导致，这个我正在研究解决方案，思路是有了，还没空去深入搞。

**Comment by lonnywong** [comment]
`Receive data timeout` 的问题已优化，如果还是遇到，也可以增加超时时间，`-t 0` 表示永不超时，`-t 100` 表示超时为 100 秒，默认是 20 秒的。

关于 Windows 作为服务器时上传慢的问题，在 https://github.com/trzsz/trzsz-go/issues/18 中讨论，希望后面能找到解决办法。

此 issue 先关了，如果有遇到其他问题，可以再提。

**Comment by lonnywong** [comment]
@wangshankun trz 上传慢的问题有解决办法了：https://github.com/trzsz/trzsz-go/issues/18#issuecomment-1556095710

**Comment by PassXml** [comment]
> 试试 https://github.com/trzsz/trzsz-go 能不能用？
> 
> SecureCRT 新建 Session 时选择 `Local Shell`，然后选择 `cmd` 或 `PowerShell` 的路径。 在里面执行 `trzsz ssh x.x.x.x` 登录到远程服务器，就可以使用 `trz` 上传，`tsz` 下载了。

如果是基于堡垒机的呢?我不能直接ssh过去必须有堡垒机的软件控制crt进行连接.

**Comment by lonnywong** [comment]
> 如果是基于堡垒机的呢?我不能直接ssh过去必须有堡垒机的软件控制crt进行连接.

不懂堡垒机的软件是怎么控制 crt 进行连接的，可能可以让堡垒机的软件接入 https://github.com/trzsz/trzsz.js 吧

**Comment by PassXml** [comment]
> > 如果是基于堡垒机的呢?我不能直接ssh过去必须有堡垒机的软件控制crt进行连接.
> 
> 不懂堡垒机的软件是怎么控制 crt 进行连接的，可能可以让堡垒机的软件接入 https://github.com/trzsz/trzsz.js 吧

我大概研究了下...堡垒机应该是在本地开启端口,然后生成了crt一个配置。直接连接这个地址。但是用户、密码这一块黑盒就不太清楚了。感觉还是比较麻烦。哎
