### ISSUE TITLE
support for Alacritty please

### ISSUE THREAD

**Issue by alayamanas** [trzsz/trzsz#22]
[Alacritty](https://github.com/alacritty/alacritty) is a fast terminal emulator, It would be great if a support added.

**Comment by lonnywong** [comment]
[Alacritty](https://github.com/alacritty/alacritty) is written in `rust`, not `js`. It's hard to support in native.

But, you can use [https://github.com/trzsz/trzsz-go](https://github.com/trzsz/trzsz-go) instead. `alias ssh="trzsz ssh"` for convenience.
