### ISSUE TITLE
无法正确显示zenity进度条

### ISSUE THREAD

**Issue by paulzhn** [trzsz/trzsz#23]
m2 macbook air，调用 `zenity --info --text=\"test\"` 可以正确弹出对话框，但trzsz不行。

版本：
- zenity v0.9.0 darwin/arm64
- tsz (trzsz) py 1.1.0
- iterm2 Build 3.4.16

**Comment by lonnywong** [comment]
zenity 安装在哪个目录？代码中用的是绝对路径，要建个软链接。
```
sudo ln -sv $(which zenity) /usr/local/bin/zenity
```

文档中有写的：https://trzsz.github.io/cn/iterm2

**Comment by lonnywong** [comment]
如果文件很小，也可能来不及弹出进度条就结束了。
