### ISSUE TITLE
mac拖拽上传centos功能失败

### ISSUE THREAD

**Issue by Alex-Shen1121** [trzsz/trzsz#25]
报错信息如下所示：
<img width="572" alt="image" src="https://user-images.githubusercontent.com/73343630/187767242-89ec4048-3902-4cbe-a4e1-9d1b0d43da8f.png">

我已经按照iterm2官方文档配置了

 > /opt/homebrew/bin/trzsz-iterm2  -p text dragfiles \(filenames)

iterm2版本 -- Build 3.5.20220831-nightly
<img width="953" alt="image" src="https://user-images.githubusercontent.com/73343630/187767401-75ace8a3-45c2-4df6-8a87-c966b0d56330.png">

**Comment by lonnywong** [comment]
iTerm2 拖文件和目录上传的功能还没有正式发布，你可以安装测试版，顺便帮测试一下。

在服务器上可以使用当前最新的正式版，不需要安装测试版。

只要在 mac 本地安装测试版就可以了。
```
sudo python3 -m pip install --upgrade -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ trzsz[iterm2]==0.2.120
```

因为你是用 homebrew 安装正式版的，所以正式版和测试版是可以共存，互不影响的。只有拖文件上传用测试版就可以了，其他可以继续用正式版。

配置拖文件上传时要用 python3 安装的路径，在刚安装完时会有提示安装到哪里的，请注意看。

**Comment by Alex-Shen1121** [comment]
> 

成功了，感谢大佬！
如果后续使用过程中遇到问题，我再提Issue。希望早日上线正式版

**Comment by lonnywong** [comment]
已发布 `v1.1.1` ，更新一下就好了。
