### ISSUE TITLE
拖拽报错

### ISSUE THREAD

**Issue by keeYuc** [trzsz/trzsz#30]
usage: trzsz-iterm2 [-h] [-v] [-p {text,zenity}] [-d DESTPATH] mode

trzsz-iterm2: error: unrecognized arguments: /Users/keeyu/Downloads/quic协议研究/quic协议研究.md

**Comment by lonnywong** [comment]
服务端 trzsz 要升级一下版本。

**Comment by lonnywong** [comment]
已发布 `v1.1.1` ，更新一下就好了。

**Comment by keeYuc** [comment]
1发自我的 iPhone在 2022年12月10日，16:32，Lonny Wong ***@***.***> 写道：﻿
已发布 v1.1.1 ，更新一下就好了。
