### ISSUE TITLE
进度条

### ISSUE THREAD

**Issue by RoterLong** [trzsz/trzsz#31]
不出现进度条

**Comment by lonnywong** [comment]
1、是不是传的文件太小？一下子就传完了，那进度条可能会不出来。

2、是 iTerm2 用 zenity 进度条？要安装 zenity ，并且要保证路径是 `/usr/local/bin/zenity`。具体可参考文档：https://trzsz.github.io/cn/iterm2

**Comment by RoterLong** [comment]
1、文件不小 100m左右
2、安装了zenity
3、triggers也照着文档配置了

是不是iterm2 的版本较低 3.4.18的版本？

**Comment by lonnywong** [comment]
可以升级 zenity 看看，他昨晚发布了个新版本，修复了个问题。

**Comment by RoterLong** [comment]
您好 进度条出来了 但是为什么会在 终端的后面显示 这个可以解决吗

&nbsp;


先厚积\再薄发
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lonny ***@***.***&gt;; 
发送时间: 2022年12月3日(星期六) 中午12:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [trzsz/trzsz] 进度条 (Issue #31)





 
可以升级 zenity 看看，他昨晚发布了个新版本，修复了个问题。

**Comment by lonnywong** [comment]
当 iTerm2 是全屏时，zenity 会在前面显示的。

刚试了一下，当 iTerm2 不是全屏时，zenity 确实不会显示在前面。这个需要 zenity 解决，不过 mac 的机制可能不好搞。

也可以试试 -p text 文本进度条，不过要求 iTerm2 是 3.5 以上的版本（ 现在还是测试版，期待 iTerm2 迟早发布 3.5 稳定版 ）。

**Comment by RoterLong** [comment]
嗯 ，好的，谢谢您的解答，多问一句哈 这个怎么设置 相同文件传上去是覆盖的呢&nbsp;


先厚积\再薄发
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lonny ***@***.***&gt;; 
发送时间: 2022年12月3日(星期六) 中午1:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [trzsz/trzsz] 进度条 (Issue #31)





 
当 iTerm2 是全屏时，zenity 会在前面显示的。
 
刚试了一下，当 iTerm2 不是全屏时，zenity 确实不会显示在前面。这个需要 zenity 解决，不过 mac 的机制可能不好搞。
 
也可以试试 -p text 文本进度条，不过要求 iTerm2 是 3.5 以上的版本（ 现在还是测试版，期待 iTerm2 迟早发布 3.5 稳定版 ）。

**Comment by lonnywong** [comment]
加上 `-y` 参数，就会覆盖同名的文件，例如 `trz -y`，`tsz -y xxx`

**Comment by lonnywong** [comment]
@RoterLong 我发现 zenity 在 v0.8.7 之前的版本是可以在前面弹出的，已经给 zenity 提了 issue。

可以自己编译一个 zenity 试试：
```
git clone https://github.com/ncruces/zenity.git
cd zenity

git checkout v0.8.7
go build ./cmd/zenity

sudo cp zenity /usr/local/bin/
```

**Comment by lonnywong** [comment]
不全屏也可以在前面弹出，不过要求不能选中 `iTerm2 -> Secure Keyboard Entry`.

**Comment by RoterLong** [comment]
<img width="699" alt="image" src="https://user-images.githubusercontent.com/38501325/206084336-0c3ff6de-e44a-4d99-86c0-3520a47ce5e8.png">
我一直没选中过 不全屏还是不能显示

**Comment by RoterLong** [comment]
我就是默认不选中的 还是不行

**Comment by lonnywong** [comment]
zenity 需要是 v0.8.7 那个版本，或者现在最新的 master 分支的（ 暂时还没有发布新的版本 ）。

**Comment by RoterLong** [comment]
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/38501325/206087598-84b5209b-a0e9-47fe-9119-6d840cd14760.png">
可以了 我拉了master的代码 编译后 替换了下 就行了 谢谢您哈
