### ISSUE TITLE
或许会和 iterm2 的托管模式冲突

### ISSUE THREAD

**Issue by evlic** [trzsz/trzsz#33]
设备 macOS ventura
iterm2 Build 3.4.17

使用 trzsz ssh xxx 之后，tmux -CC attach -t xx 托管 tmux 会失控

**Comment by lonnywong** [comment]
你使用 `iTerm2` + `tmux -CC`，就不要使用 [trzsz-go](https://github.com/trzsz/trzsz-go) 了，用原生的 ssh 就好了（ ssh 命令不要带上 trzsz ）。

iTerm2 的配置可以参考 https://trzsz.github.io/cn/iterm2
