### ISSUE TITLE
tmux底部的状态栏会慢慢变多。

### ISSUE THREAD

**Issue by K-JW** [trzsz/trzsz#34]
如图

![image](https://user-images.githubusercontent.com/12265263/227690568-bb128f1f-a9ea-446c-8644-1b9bb137a2f5.png)

**Comment by lonnywong** [comment]
@K-JW 可以提供一下使用的环境吗？
1、在客户端，使用的是什么终端，什么版本的？`trzsz` 使用哪个版本？
2、在服务端，使用的 tmux 是什么版本的？运行 tmux 的命令是怎样的？有没有分屏？`trzsz` 使用哪个版本？

**Comment by K-JW** [comment]
@lonnywong   感谢作者的及时回复。我在重启服务器的 tmux 会话之后，这个问题不能复现了。给你添麻烦了。

我的客户端是 Windows10 + Windows Terminal + trzsz (1.0.0)

服务端是 Debian bullseye + tmux (3.1) + trzsz (1.1.1)

**Comment by lonnywong** [comment]
如果服务器不重启的话，可能 `reset` 命令也可以还原一些设置。
