### ISSUE TITLE
Are there plans to support  windows terminal

### ISSUE THREAD

**Issue by llanc** [trzsz/trzsz#35]
As the title

**Comment by lonnywong** [comment]
Already supported. Try https://github.com/trzsz/trzsz-go

**Comment by llanc** [comment]
![image](https://user-images.githubusercontent.com/31590534/228105383-1f01aff0-4b18-4fff-9a62-e4b72da8b3ff.png)

When I use the windows terminal to connect to the debian server, I only get the output as shown in the picture when I type trz, and there is no other response.

As far as I know, windows terminal does not support Zmodem protocol [#1602](https://github.com/microsoft/terminal/issues/1602)，this makes tools like lrzsz unusable. 

Is trzsz also implemented based on the Zmodem protocol? Maybe using sftp protocol to support windows terminal is a good way.

The windows terminal version I use is 1.16.10262.0.

**Comment by lonnywong** [comment]
How do you login to the debian server?

You need to install [ttps://github.com/trzsz/trzsz-go](https://github.com/trzsz/trzsz-go) on Windows first:
```
scoop bucket add extras
scoop install trzsz
```

And then login to the server with `trzsz` command:
```
trzsz ssh xxx@x.x.x.x
```

**Comment by llanc** [comment]
It works！
Sorry I didn't read the README carefully，I thought it only needs to be installed on the server side like lrzsz.
