### ISSUE TITLE
secureCRT里面无法使用

### ISSUE THREAD

**Issue by indextank** [trzsz/trzsz#36]
使用rz/sz都可以正常上传下载
通过sudo python3 -m pip install --upgrade trzsz 安装后无法正常使用。

同一台服务器，尝试了bash和zsh都无法正常使用。
错误提示如下：

➜  /opt trz
::TRZSZ:TRANSFER:R:1.1.2:7989870477400
#fail:eJzzzCtJLSoqLShJTQEAGxMElw==
Interrupted

➜  /opt tsz slow.tar.gz 
::TRZSZ:TRANSFER:S:1.1.2:7989872050500
#fail:eJzzzCtJLSoqLShJTQEAGxMElw==
Interrupted

**Comment by lonnywong** [comment]
SecureCRT 和 xshell 类似 https://github.com/trzsz/trzsz/issues/18#issuecomment-1484548571 ，都是非开源的，需要对应的公司支持才可以。

如果有本地 shell，例如 Windows Terminal 等，是可以使用 https://github.com/trzsz/trzsz-go 的。

在 ssh 登录到选程服务器时，在前面加上 trzsz，如 `trzsz ssh xxx@x.x.x.x` 登录服务器，就可以用 trz / tsz 上传和下载了。

**Comment by lonnywong** [comment]
@indextank 可以试试 https://github.com/trzsz/trzsz-ssh
在 SecureCRT 中打开一个本地 shell，然后用 tssh 登录，就可以用 trz / tsz 上传和下载了。
