### ISSUE TITLE
windows OS 报错

### ISSUE THREAD

**Issue by LittePrince** [trzsz/trzsz#38]
PS C:\Windows\system32> trzsz ssh
trzsz : The term 'trzsz' is not recognized as the name of a cmdlet, function, script file, or operable program. Check t
he spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ trzsz ssh
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (trzsz:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by lonnywong** [comment]
是没有安装 https://github.com/trzsz/trzsz-go ？

一种安装办法是，先安装 scoop https://scoop.sh/ ，然后安装 trzsz：
```
scoop bucket add extras
scoop install trzsz
```

另一种，在 https://github.com/trzsz/trzsz-go/releases 这里下载适合的安装包，然后安装。如果不是 setup 那些，要把 zip 解压后的放在某个程序路径下，如 system32 下，或者自己改一下 Path 环境变量。

**Comment by lonnywong** [comment]
Windows 现在推荐使用 https://github.com/trzsz/trzsz-ssh ，解决了 trz 上传慢的问题。
