### ISSUE TITLE
目录一定要 -d 么，不能自动识别？

### ISSUE THREAD

**Issue by cn-src** [trzsz/trzsz#39]

**Comment by lonnywong** [comment]
`alias tsz="tsz -d"` ?

**Comment by cn-src** [comment]
> `alias tsz="tsz -d"` ?
忘了可以这样，请问客户端和服务端都需要安装么？能只在客户端安装么。

**Comment by lonnywong** [comment]
服务端是必须要安装的，你从 https://github.com/trzsz/trzsz-go/releases 下载个对应的二进制，放在某个目录，然后 `./trz` 这样也行。

客户端要看你用的是什么，有些客户端不用安装。
