### ISSUE TITLE
我配置了之后并不能成功使用tsz和trz

### ISSUE THREAD

**Issue by MF-ReStart** [trzsz/trzsz#4]
![image](https://user-images.githubusercontent.com/50358485/147203838-f1abfc65-3604-40aa-9abc-77dd263bcb2b.png)

**Comment by MF-ReStart** [comment]
![image](https://user-images.githubusercontent.com/50358485/147203962-68d513f8-49f6-43a1-89f3-5284849fb8c0.png)

**Comment by lonnywong** [comment]
看起来是 `:(:TRZSZ:TRANSFER:[SR]:\d+\.\d+\.\d+)` 没有配对，和这个图对比一下有没有出入？

![](https://trzsz.github.io/images/config.png)

**Comment by MF-ReStart** [comment]
![image](https://user-images.githubusercontent.com/50358485/147206156-f0b29d84-46f7-4c4c-9ab9-12111c40fef0.png)
我是直接复制粘贴的。

**Comment by MF-ReStart** [comment]
会不会是我的Python版本问题呢

**Comment by lonnywong** [comment]
最下面 Use interpolated strings for parameters 不要选中试试？

**Comment by MF-ReStart** [comment]
这是我的iterm2的command登录命令/usr/local/bin/sshpass -p '0' ssh -p 22 -t root@10.10.110.31 "tmux attach -CC first-session || tmux  new -s first-session"

**Comment by MF-ReStart** [comment]
关闭了

**Comment by lonnywong** [comment]
> 最下面 Use interpolated strings for parameters 不要选中试试？

如果要选中下面的 `Use interpolated strings for parameters` 也可以，
Parameters 要改成 `/usr/local/bin/trzsz-iterm2 \(matches[1])`

**Comment by lonnywong** [comment]
> ![image](https://user-images.githubusercontent.com/50358485/147206890-8e00c057-5e8c-464e-b2f7-100326f48bbe.png) 关闭了Use interpolated strings for parameters，现在是这个报错信息

嗯，有时会报这个错，多试几次会有成功的。
这个就是我在 https://github.com/trzsz/trzsz/issues/1#issuecomment-999968473 中说的问题，代码已经改好，等我测试完，确保没有引入新的问题，就会发布。

**Comment by MF-ReStart** [comment]
到时候我要怎么更新客户端和服务器端程序呢

**Comment by lonnywong** [comment]
> 到时候我要怎么更新客户端和服务器端程序呢

跟安装时一样的（已经加了 --upgrade 选项）

服务端：
```
sudo python3 -m pip install --upgrade trzsz-libs trzsz-svr
```

客户端：
```
sudo python3 -m pip install --upgrade trzsz-libs trzsz-iterm2
```
