### ISSUE TITLE
control + c 取消时会输出很多日志（基本必现）

### ISSUE THREAD

**Issue by liqyu** [trzsz/trzsz#40]
trzsz + iterm2

**Comment by liqyu** [comment]
<img width="570" alt="image" src="https://user-images.githubusercontent.com/129363032/233967945-f914befb-0556-4c8c-9628-9dc110dc359f.png">

**Comment by lonnywong** [comment]
取消是指  ctrl + c ？

**Comment by liqyu** [comment]
是的，control + c，前面说错了

**Comment by lonnywong** [comment]
是当前最新的 1.1.2 版本？代码中专门针对这种情况做了处理的。在我的环境，一般不会出现这情况。主要是通过 sleep 一小段时间来解决的，可能跟网络和机器性能有关，sleep 的时间在你的环境不是很适配。

**Comment by liqyu** [comment]
是最新的版本

**Comment by lonnywong** [comment]
你用的是 iTerm2 ，`ctrl + c` 的逻辑在这：
https://github.com/trzsz/trzsz/blob/a7d65b1729d5fa3ac604386f818f21c9d901e681/trzsz-libs/trzsz/libs/utils.py#L484-L487

会自动计算每一次传输的最大时间，在 `ctrl + c` 退出时，至少等待 2 倍的时间，并且这个时间不小于 0.5 秒，即 `clean_timeout` 变量的值。

iterm2 客户端在 `ctrl + c` 退出时，会走到这个逻辑：
https://github.com/trzsz/trzsz/blob/a7d65b1729d5fa3ac604386f818f21c9d901e681/trzsz-libs/trzsz/libs/utils.py#L516-L517

在 `clean_input` 里会等待 `clean_timeout` 的时间，丢弃收到的内容（ 即你截图显示的那些 ）：
https://github.com/trzsz/trzsz/blob/a7d65b1729d5fa3ac604386f818f21c9d901e681/trzsz-libs/trzsz/libs/utils.py#L181-L190
 
@liqyu 你可以在 mac 上找到这几行相关的代码，改一改，调一调，看看问题出在哪里了？例如：
```py
def clean_input(timeout): 
    with open('/tmp/debug1', 'w') as f:
        f.write(f'timeout = {timeout}\n')
    begin_time = time.time()
     if is_windows: 
         time.sleep(timeout) 
         return 
     while True: 
         r, w, x = select.select([sys.stdin], [], [], timeout) 
         if not r: 
             break 
         if not os.read(sys.stdin.fileno(), 10240): 
             break 
    end_time = time.time()
    with open('/tmp/debug2', 'w') as f:
        f.write(f'clean time = {end_time - begin_time}\n')
```

**Comment by liqyu** [comment]
我这样处理了一下
```python
def clean_input(timeout):
    if is_windows:
        time.sleep(timeout) 
        return
    try:
        while True:
            r, w, x = select.select([sys.stdin], [], [], timeout)
            if not r:
                break
            if not os.read(sys.stdin.fileno(), 10240):
                break
    except KeyboardInterrupt:
        pass
```

**Comment by lonnywong** [comment]
> 我这样处理了一下
> 
> ```python
> def clean_input(timeout):
>     if is_windows:
>         time.sleep(timeout) 
>         return
>     try:
>         while True:
>             r, w, x = select.select([sys.stdin], [], [], timeout)
>             if not r:
>                 break
>             if not os.read(sys.stdin.fileno(), 10240):
>                 break
>     except KeyboardInterrupt:
>         pass
> ```

这样有用不？

**Comment by lonnywong** [comment]
那问题是找到了，看来你是按了多次 `ctrl + c`，而我在测试时都只按了一次。

除了你列出的这里可能会被异常中断，还有进入 clean_input 之前也可能会被中断。

最好是在这里加个标记，只触发一次：
https://github.com/trzsz/trzsz/blob/a7d65b1729d5fa3ac604386f818f21c9d901e681/trzsz-libs/trzsz/libs/utils.py#L484-L487

@liqyu 你有空可以提个 PR 过来，或者等我周末来搞一下。

**Comment by liqyu** [comment]
不是多次，我就按了一次也会出现，应该不是次数导致的。
chatgpt的回答：因为 KeyboardInterrupt 所抛出的异常在 select.select() 方法的监控下，看起来像是一个 I/O 事件发生了；在有些情况下也会产生一些不必要的输出，从而混淆了控制台中的输出日志。

**Comment by lonnywong** [comment]
有点奇怪，至少应该在 while 里面 try 才生效的。

**Comment by lonnywong** [comment]
@liqyu 你用的 Python 是哪个版本的？

https://docs.python.org/3/library/select.html

Changed in version 3.5: The function is now retried with a recomputed timeout when interrupted by a signal, except if the signal handler raises an exception (see [PEP 475](https://peps.python.org/pep-0475/) for the rationale), instead of raising [InterruptedError](https://docs.python.org/3/library/exceptions.html#InterruptedError).

3.5 之后的版本是不会抛出 KeyboardInterrupt 的了，会自动重试。

**Comment by liqyu** [comment]
Python 2.7.5
服务器自带的，懒得弄环境了（不是主要运行python的服务器）。

**Comment by lonnywong** [comment]
@liqyu 这个关闭了，是已经确认是哪里的问题，或者确认了改哪里可以解决？

**Comment by liqyu** [comment]
我就是上面那样加了try-except后就没有在打印日志了，对于我来说是有用的

**Comment by liqyu** [comment]
改的是服务器上的trzsz

**Comment by lonnywong** [comment]
@liqyu 有空的话，安装个测试的版本，看看有没有解决这个问题？

1. 卸载正式版 `python2 -m pip uninstall trzsz-libs trzsz-svr trzsz`
2. 安装测试版 `python2 -m pip install -i https://test.pypi.org/simple/ trzsz==0.2.136`
