### ISSUE TITLE
Windowns Terminal Directly Start WSL/WSL2不支持trzsz

### ISSUE THREAD

**Issue by cowboysss** [trzsz/trzsz#41]
WIN11平台
使用Windowns Terminal时候不支持trzsz下载数据。
目前临时解决方式使用trzsz通过ssh登录到WSL2进行使用。

**Comment by lonnywong** [comment]
是的，Windows Terminal 并没有直接支持 trzsz，因此需要先开一个本地 shell（ wsl 不算本地 shell ），然后用 https://github.com/trzsz/trzsz-go 来间接支持。

直接支持 trzsz 的终端也有，如 tabby 和 electerm，你可以试试，上传速度也会快很多。

**Comment by lonnywong** [comment]
@cowboysss 在 WSL/WSL2 中，现在可以用 https://github.com/trzsz/trzsz-ssh

需要注意的是，要安装 Windows 版本，然后在 WSL/WSL2 中使用 Windows 版本，并且要带着 `.exe` 后缀使用，如：

```
/mnt/c/Users/your_name/go/bin/tssh.exe xxx
```

为了使用方便，可以加个 alias ：
```
alias tssh="/mnt/c/Users/your_name/go/bin/tssh.exe"
```

ssh 配置是使用 Windows 的，在 `C:\Users\your_name\.ssh\` 下。
