### ISSUE TITLE
Error while using in nested sessions

### ISSUE THREAD

**Issue by mstenz** [trzsz/trzsz#42]
I have a ttyd with 2 nested byobu sessions (login from console to different server) then calling tsz, this happens: 

```
[TrzszError] colon: eJyTjja0NjEqko42MbI29AAAGFwDSw==
    at ji.<anonymous> (https://xxxxxxxxxx.com/:1:645051)
    at Generator.next (<anonymous>)
    at o (https://xxxxxxxxxx.com/:1:580425)
goroutine 1 [running]:
runtime/debug.Stack()
        /usr/lib/go-1.18/src/runtime/debug/stack.go:24 +0x65
github.com/trzsz/trzsz-go/trzsz.NewTrzszError({0xc0000f8000, 0xd8}, {0xc0000147e8, 0x4}, 0x1)
        /build/trzsz-T3vCFF/trzsz-1.0.0.1/trzsz/comm.go:171 +0x272
github.com/trzsz/trzsz-go/trzsz.(*TrzszTransfer).recvCheck(0x5582d1?, {0x5582e1, 0x4}, 0x3c?, 0xc00011c000?)
        /build/trzsz-T3vCFF/trzsz-1.0.0.1/trzsz/transfer.go:191 +0x152
github.com/trzsz/trzsz-go/trzsz.(*TrzszTransfer).recvString(0x0?, {0x5582e1?, 0x4?}, 0x86?)
        /build/trzsz-T3vCFF/trzsz-1.0.0.1/trzsz/transfer.go:225 +0x25
github.com/trzsz/trzsz-go/trzsz.(*TrzszTransfer).sendFileName(0x53ad60?, 0xc000078280, 0x0?, {0x0?, 0x0})
        /build/trzsz-T3vCFF/trzsz-1.0.0.1/trzsz/transfer.go:473 +0xce
github.com/trzsz/trzsz-go/trzsz.(*TrzszTransfer).sendFiles(0xc00011c000, {0xc00000e0b0, 0x1, 0x0?}, {0x0, 0x0})
        /build/trzsz-T3vCFF/trzsz-1.0.0.1/trzsz/transfer.go:590 +0x331
github.com/trzsz/trzsz-go/trzsz.sendFiles(0xc00011c000?, {0xc00000e0b0, 0x1, 0x1}, 0xc000074ba0, 0x416001?, 0xc000036690?)
        /build/trzsz-T3vCFF/trzsz-1.0.0.1/trzsz/tsz.go:88 +0x19f
github.com/trzsz/trzsz-go/trzsz.TszMain()
        /build/trzsz-T3vCFF/trzsz-1.0.0.1/trzsz/tsz.go:172 +0x8c5
main.main()
        /build/trzsz-T3vCFF/trzsz-1.0.0.1/cmd/tsz/main.go:33 +0x19
```
Any idea what might be wrong?

**Comment by lonnywong** [comment]
Is the byobu using tmux?

**Comment by mstenz** [comment]
I think so, If I remember correct this is default on Ubuntu machines, how I can make sure and find out? the first session is definitive using tmux

**Comment by mstenz** [comment]
```
root@xxxxxxxxx:~# ps aux | grep tmux
root     3031534  0.0  0.0   8316  4020 pts/5    S+   09:43   0:00 tmux -u -2 -f /usr/share/byobu/profiles/tmuxrc new-session -n - /usr/bin/byobu-shell
root     3031569  0.3  0.0   9052  4368 ?        Ss   09:43   0:00 tmux -u -2 -f /usr/share/byobu/profiles/tmuxrc new-session -n - /usr/bin/byobu-shell
```

so I think yes, its tmux

**Comment by lonnywong** [comment]
If it's using tmux, trzsz should work.

Try the following command and show me the output:
```sh
tmux display-message -p '#{client_tty}:#{client_control_mode}:#{pane_width}'
```

**Comment by mstenz** [comment]
in 2nd session this is the output: 

> no server running on /tmp/tmux-0/default

in 1st session this is the output:

> /dev/pts/7:0:188

If i just start tmux with "tmux" and then try it in the 2nd session it works.

**Comment by lonnywong** [comment]
The 1st session should work, and the 2nd doesn't.

**Comment by mstenz** [comment]
> The 1st session should work, and the 2nd doesn't.

Yes exactly that is the case, but I need to have 2nd working.

**Comment by lonnywong** [comment]
You need to find a way to make the 2nd session work with tmux. Are they in the same server?

**Comment by mstenz** [comment]
These are different servers, but both are Ubuntu machines. I have not understood how trzsz works technically, so I don't know what requirements are needed to make it work.

**Comment by lonnywong** [comment]
Do they both have tmux?

**Comment by lonnywong** [comment]
https://www.byobu.org/documentation

byobu  currently  defaults to using [tmux](https://manpages.ubuntu.com/manpages/kinetic/en/man1/tmux.1.html)(1) (if present) as the backend, however, this can be overridden with the [byobu-select-backend](https://manpages.ubuntu.com/manpages/kinetic/en/man1/byobu-select-backend.1.html)(1) utility.

trzsz support tmux only, doesn't support screen.

**Comment by mstenz** [comment]
yes. I also think tmux was enabled before anyhow, so I have set with byobu-select-backend explicitly berfore, but this doesn't change anything and the same error message appears. 

so do you think this is a problemy with tmux, byobu or trzsz?

**Comment by mstenz** [comment]
this is the session tree:

-> Login via ttyd and webbrowser to a K8s Container (session 1), byobu is running automatically at login
--> From there login via ssh to a classic vm (session 2) in different network, byobu can be started manually and works

a direct login to session2 (the vm) is not possible. the first session acts like a bastion

**Comment by mstenz** [comment]
I just did one more test and instead of downloading I was now uploading a file. Exactly 1024 Bytes of the file were transferred, then the same error message appeared.

**Comment by lonnywong** [comment]
trzsz doesn't support that byobu/tmux running in the middle. Can you disable byobu on the 1st? You can use byobu on the 2nd.

**Comment by mstenz** [comment]
I see. I have for experimental reasons logged in without byobu to first session and it works now even in the 2nd session no byobu is running. 
Unfortunately it is a hard requirement that for 1st session users are using byobu because there are specific security and configuration settings applied that are loaded together with it. So for production use i cannot get rid of it. 
Is there any way to make such a configuration workable?

**Comment by lonnywong** [comment]
It's hard to do that.
It just occurred to me that there's a way that may work. Make a trzsz relay program running on the 1st.

**Comment by mstenz** [comment]
hm. that would be an idea. I am not able to create such a relay program. 
But thank you for your support so far. :)

**Comment by lonnywong** [comment]
I might do it when I get some free time.

**Comment by mstenz** [comment]
> I might do it when I get some free time.

this for sure would be a great thing, thank you. I think probably such scenario is quite common for security or operations reasons, so probably a lot of others would find this very usefull as well.

**Comment by lonnywong** [comment]
Can you compile [https://github.com/trzsz/trzsz-go](https://github.com/trzsz/trzsz-go) and try it? 

On the 1st, use `trzsz -r ssh 2nd` to login to 2nd, then you can use `trz` / `tsz` on the 2nd.

**Comment by mstenz** [comment]
Thank you for creating something. Unfortunately, I do not know how to compile this. 
I was not aware before that you need to establish the connection via trzsz, we do not use a regular ssh connection but the "az vm ssh" command to log in to the 2nd session. would this work with the relay as well?

**Comment by lonnywong** [comment]
Install golang 1.20: https://go.dev/dl/ , then compile `trzsz`:
```
git clone https://github.com/trzsz/trzsz-go.git
cd trzsz-go
make
```
The binary `trzsz` is in the `bin` directory.

`trzsz -r az vm ssh` should work.

`az vm trzsz -r ssh` may work too, it depends on the `az`.

**Comment by lonnywong** [comment]
@mstenz [v1.1.0](https://github.com/trzsz/trzsz-go/releases/tag/v1.1.0) released.

**Comment by lonnywong** [comment]
@mstenz does  `trzsz -r` work?

If dialogs keep popup, try:
`go install github.com/trzsz/trzsz-go/cmd/trzsz@1e59524`
