### ISSUE TITLE
how to connect to linux server?

### ISSUE THREAD

**Issue by Rockflow** [trzsz/trzsz#43]
How to set up the linux server ? Can you give some example

**Comment by lonnywong** [comment]
1. Install [trzsz-go](https://github.com/trzsz/trzsz-go) on the Linux server.
2. Install [trzsz-go](https://github.com/trzsz/trzsz-go) on the Linux desktop.
3. Use `trzsz ssh x.x.x.x` to log in to the Linux server.
4. Use `trz` to upload files. Use `tsz xxx` to download `xxx` file.

**Comment by lonnywong** [comment]
Read the document: https://trzsz.github.io/
