### ISSUE TITLE
怎么在 k8s pod 中使用 trzsz

### ISSUE THREAD

**Issue by destinytaoer** [trzsz/trzsz#44]
我通过 k8s exec 接口连接到 pod 中的 bash 命令行，在 bash 中通过 `sudo python3 -m pip install --upgrade trzsz` 安装了 trzsz

前端使用 trzsz.js 来实现，但是当我使用 trz 命令时，在上传过程中会卡住，消息中也只传递了部分内容就不再传输了。一段时间后，就超时断开了，有时候甚至会卡在进度条中

同样的前端实现，在我本地使用 node-pty 实现的终端连接中，不会出现问题。是否有遇到过这种问题，有没有什么建议？

另一个问题是取消或者中断后，不完整的文件仍然会保留，不会被删除

![image](https://github.com/trzsz/trzsz/assets/27852774/5c4d02de-e88d-4585-bed5-5b2c8805a1ba)

**Comment by lonnywong** [comment]
> 前端使用 trzsz.js 来实现，但是当我使用 trz 命令时，在上传过程中会卡住，消息中也只传递了部分内容就不再传输了。一段时间后，就超时断开了，有时候甚至会卡在进度条中

你是用 websocket 还是什么方式跟远程连接的？如果是 websocket ，你 F12 看一下那个链接（ 可能需要先打开 F12 再让应用创建连接 ），所有传输的报文都能看到的，可以看到停在哪里了。

> 另一个问题是取消或者中断后，不完整的文件仍然会保留，不会被删除

后面有空会加个取消确认的功能，确认取消时要选择是否删除已传输的文件。在 https://github.com/trzsz/trzsz-go/issues/27#issue-1716641588 第一点也提出了类似建议。

**Comment by destinytaoer** [comment]
> 你是用 websocket 还是什么方式跟远程连接的？如果是 websocket ，你 F12 看一下那个链接（ 可能需要先打开 F12 再让应用创建连接 ），所有传输的报文都能看到的，可以看到停在哪里了。

@lonnywong 
![trz](https://github.com/trzsz/trzsz/assets/27852774/a8eb3a8e-17e0-4a9a-8e97-4e25b93a6653)

**Comment by destinytaoer** [comment]
这个卡在进度条这里了，但是我看到 websocket 消息里面其实是有返回超时消息的，就是没有输出到终端中
![image](https://github.com/trzsz/trzsz/assets/27852774/cb5028a4-13bb-4dd0-84d2-4223171bc497)

**Comment by lonnywong** [comment]
前面那个问题出在 87.4 kB ( 18:52:19.163 ）那个包，服务器上的 trz 收不完整，可能是被你的某段逻辑截断了。

你可以限制一下每次上传的包大小试试，如 `trz -B 10k` 这样，可能就能成功了，但是这样会导致速度变慢。

至于问题，你查查服务器上哪段逻辑限制了单个上传包的长度。

**Comment by destinytaoer** [comment]
> 你可以限制一下每次上传的包大小试试，如 trz -B 10k 这样，可能就能成功了，但是这样会导致速度变慢。
@lonnywong 刚刚试了一下，限制了大小确实可以上传成功

**Comment by destinytaoer** [comment]
@lonnywong 对于限制传输的包大小，是只能通过命令来设置吗，前端 trzsz.js 里面可以配置限制吗

**Comment by lonnywong** [comment]
那问题应该很明确了，估计是哪里限制了大小，超长就截断，或者直接丢掉了。

**Comment by lonnywong** [comment]
> @lonnywong 对于限制传输的包大小，是只能通过命令来设置吗，前端 trzsz.js 里面可以配置限制吗

trzsz.js 中设置不了。你可以在服务器上 `alias trz="trz -B10k"` 这样设置，然后 `trz` 就自然限制了 10K 大小了。

**Comment by destinytaoer** [comment]
> trzsz.js 中设置不了。你可以在服务器上 alias trz="trz -B10k" 这样设置，然后 trz 就自然限制了 10K 大小了。

好的，非常感谢~

**Comment by destinytaoer** [comment]
我发现 trz 每次发送包都会等待响应一个

**Comment by destinytaoer** [comment]
还有一些不一样的地方是：
1. rz 是传输完成之后，再合并文件，trz 是边传边写入
2. sz 是下载完成之后，拿到整个文件内容再合并下载，tsz 也是边传边写

lrzsz 中断就不会有问题残留，而 trzsz 会。lrzsz 就是会缓存文件，大文件时压力比较大，好像还有缓存溢出问题

**Comment by lonnywong** [comment]
是这样的，你看到的发送了，并不代表远程服务器就收完了。当远程服务器收完之后，就会回一个 `SUCC`，然后再发下一个包。

这个 `SUCC` 确认，是为了能尽早检测出是不是出问题了，会浪费一个 RTT 的时间。如果每次传的包很小，又浪费一个 RTT 的时间，对速度的影响就会比较大。如果每次传的包较大，浪费一个 RTT 的时间，其实也问题不大。

为了提高速度，会有一个自动适配的过程，每次传的包大小都翻倍，直到每个包所需的时间在 0.5 - 1 秒之间。

有文件残留的问题，其实好解决，人工删一下，或者以后加个功能自动删，现在 `trz -y` 也会自动覆盖重传。trzsz 边传边写就没有上限，只要网络稳定就可以传很大的文件。不删除也有另一个好处，以后还准备加一个断点续传的功能。

**Comment by lonnywong** [comment]
> 我发现 trz 每次发送包都会等待响应一个成功消息

我仔细再想了一下，好像也可以做成异步接收这个 SUCC 的 ack，在 ping 延迟特别大的环境，可以提高不少的速度。

会在 go 版 https://github.com/trzsz/trzsz-go 先实现，客户端和服务端都同时升级才会生效，py 和 js 版都还没有实现流水线的传输，会晚一些支持。

**Comment by destinytaoer** [comment]
> 有文件残留的问题，其实好解决，人工删一下，或者以后加个功能自动删，现在 trz -y 也会自动覆盖重传。trzsz 边传边写就没有上限，只要网络稳定就可以传很大的文件。不删除也有另一个好处，以后还准备加一个断点续传的功能。

残留文件的文件名是一样的，在终端看起来没有区别，就可能会给用户上传完成的错觉，可以考虑一些临时文件。

还有一个问题是，在 web terminal 的场景里面，我更多的是希望 trzsz.js 能够去做更多的配置，来限制用户对 trzsz 的使用。类似我这种云原生开发的场景下，我必须要限制用户对 k8s pod 的访问，比如上传下载速度、文件大小、切片大小、文件数量等等。当然如果 web terminal 是用户本地使用的场景，不考虑这些都是没问题的

**Comment by lonnywong** [comment]
> 还有一个问题是，在 web terminal 的场景里面，我更多的是希望 trzsz.js 能够去做更多的配置，来限制用户对 trzsz 的使用。类似我这种云原生开发的场景下，我必须要限制用户对 k8s pod 的访问，比如上传下载速度、文件大小、切片大小、文件数量等等。当然如果 web terminal 是用户本地使用的场景，不考虑这些都是没问题的

这个太定制化了，不太好搞。

**Comment by destinytaoer** [comment]
> 我仔细再想了一下，好像也可以做成异步接收这个 SUCC 的 ack，在 ping 延迟特别大的环境，可以提高不少的速度。

我看 lrzsz 的 [Zmodem 协议](https://zh.wikipedia.org/wiki/ZMODEM) 就是类似这样干的

![image](https://github.com/trzsz/trzsz/assets/27852774/267cf53b-c6b9-4363-a895-485cee88fc2c)

**Comment by destinytaoer** [comment]
> 这个太定制化了，不太好搞。

我会尝试在本地修改 trzsz.js 代码来实现自己的定制化需求，其中有一点就是 trzsz 用的 File System Access api 的兼容性也不太好，并且这个 api 在下载文件时，保存文件位置需要做各种检查，用户体验很差
