### ISSUE TITLE
almalinux下的问题，1.1.2版本

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [trzsz/trzsz#45]
我从windows terminal用tssh连接，服务端装的python版本trzsz，如果是centos8.5，运行正常，另外一台机器，装的是 AlmaLinux 9.1，除了操作系统，其他变量都一样，就报错。python使用的miniconda，3.10的版本
![image](https://github.com/trzsz/trzsz/assets/2133400/244739b8-2e64-4c79-b0ad-92b7e15f5a67)
按理说这系统官方承诺100%兼容的，不知能看出什么不。
另外trzsz-go版本我也装了，问题一样，堆栈信息不同而已。

**Comment by lonnywong** [comment]
trzsz 几个实现之间，是互相兼容的。

从这个报错来看，可能跟你服务器上的 shell 环境有关系，有没有在用 screen 或 byobu 等？

**Comment by FinallyFinancialFreedom** [comment]
没，连zsh都没用，就原始的bash。在不在tmux下执行trzsz都没区别，一样的错。

**Comment by lonnywong** [comment]
```
tssh --tracelog xxx

echo -e '<ENABLE_TRZSZ_TRACE_LOG\x3E'
# 你会看到一个日志路径，在本地电脑中的

trz

# 出错后
echo -e '<DISABLE_TRZSZ_TRACE_LOG\x3E'
```

把日志发到我邮箱 lonnywong@qq.com ，我有空时看看。

**Comment by lonnywong** [comment]
![image](https://github.com/trzsz/trzsz/assets/20320324/21ab6996-d754-46c5-9525-03f0c2f1bfb5)

我看你的服务器会输出这样一条东西，就是它影响了 trzsz 传输数据。
tmux 也会输出类似的东西，trzsz 是专门针对  tmux 做了适配的。我不知道这条是什么工具，但我想你应该知道它是什么。

**Comment by FinallyFinancialFreedom** [comment]
真没看出是啥来，可能是tmux的主题配置，https://github.com/gpakosz/.tmux
彻底重装系统了。验证如果纯tmux没有任何配置，是可以用的。有主题配置就不行。但相同主题配置在centos8.5是可以的，在ubuntu下也是可以的。可能是perl版本啥的问题。
不研究了，这问题比如容易绕过去。

**Comment by lonnywong** [comment]
@FinallyFinancialFreedom 可能跟 tmux 的色彩与编码有关系。
当 `tmux` 不行时，一般 `tmux -2` 就可以，或者再试试 `tmux -2 -u`，
`-2` 是强制 tmux 使用 256 色彩，也有其他的配置方式的，可以搜一下。

**Comment by lonnywong** [comment]
@finviman 可能 tmux 主题的问题跟下面这行配置有关系，有空可以试试继续用这个主题，但是把这行改一下。

https://github.com/gpakosz/.tmux/blob/fd1bbb56148101f4b286ddafd98f2ac2dcd69cd8/.tmux.conf#L50
```
set -g status-interval 10     # redraw status line every 10 seconds
```

只要设置成 `0` 就是禁止刷新了：
```
set -g status-interval 0
```
