### ISSUE TITLE
trz upload failed

### ISSUE THREAD

**Issue by zkcrescent** [trzsz/trzsz#47]
Traceback (most recent call last):

  File "/opt/homebrew/lib/python3.11/site-packages/trzsz/iterm2/main.py", line 381, in main

    upload_files(args, loop, connection, session, False, remote_is_windows)

  File "/opt/homebrew/lib/python3.11/site-packages/trzsz/iterm2/main.py", line 186, in upload_files

    config = transfer.recv_config()

             ^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/homebrew/lib/python3.11/site-packages/trzsz/libs/transfer.py", line 80, in recv_config

    config = utils.recv_json('CFG', True)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/homebrew/lib/python3.11/site-packages/trzsz/libs/utils.py", line 564, in recv_json

    dic = recv_string(typ, may_has_junk)

          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/homebrew/lib/python3.11/site-packages/trzsz/libs/utils.py", line 479, in recv_string

    return decode_buffer(recv_check(typ, may_has_junk)).decode('utf8')

                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/homebrew/lib/python3.11/site-packages/trzsz/libs/utils.py", line 450, in recv_check

    raise TrzszError(encode_buffer(line.encode('utf8')), 'colon')

trzsz.libs.utils.TrzszError: [TrzszError] colon: eJwDAAAAAAE=

**Comment by lonnywong** [comment]
服务器是什么环境（ 操作系统、有没有运行 tmux 或 screen 等 ）？
在服务器上运行 `trz -v` 看看是什么版本。
在本地电脑上运行 `trzsz-iterm2 -v` 看看是什么版本。

**Comment by zkcrescent** [comment]
Apple M1 Pro  macOS 13.5.1 , ITERM + TMUX ,  
服务器版本: trz (trzsz) go 1.1.6
本地版本: trzsz-iterm2 (trzsz) py 1.1.4

**Comment by lonnywong** [comment]
本地安装 https://github.com/trzsz/trzsz-go 试试看会不会有同样的问题？
```
brew install trzsz-go
brew link --overwrite trzsz-go
```

然后这样登录服务器：
```
trzsz ssh xxx
```

然后 `trz` 上传，看看会不会有类似的问题？

**Comment by zkcrescent** [comment]
> @zkcrescent 你是不是先运行 tmux ，然后再运行 ssh 登录远程服务器，然后 trz 上传文件的？

对的

**Comment by zkcrescent** [comment]
> 本地安装 https://github.com/trzsz/trzsz-go 试试看会不会有同样的问题？
> 
> ```
> brew install trzsz-go
> brew link --overwrite trzsz-go
> ```
> 
> 然后这样登录服务器：
> 
> ```
> trzsz ssh xxx
> ```
> 
> 然后 `trz` 上传，看看会不会有类似的问题？

该方法可行~感谢帮助

**Comment by zkcrescent** [comment]
顺带问一句如何上传的时候保证权限一致上传

**Comment by lonnywong** [comment]
> > @zkcrescent 你是不是先运行 tmux ，然后再运行 ssh 登录远程服务器，然后 trz 上传文件的？
> 
> 对的

文档有写的（ 第一条 ）：https://github.com/trzsz/trzsz#trouble-shooting
中文：https://trzsz.github.io/cn/

另外，也可以用 [tssh](https://github.com/trzsz/trzsz-ssh) 代替 `trzsz ssh`，速度会更快。

**Comment by lonnywong** [comment]
> 顺带问一句如何上传的时候保证权限一致上传

现在还不支持，等我有空实现一下。

**Comment by zkcrescent** [comment]
> > > @zkcrescent 你是不是先运行 tmux ，然后再运行 ssh 登录远程服务器，然后 trz 上传文件的？
> > 
> > 
> > 对的
> 
> 文档有写的（ 第一条 ）：https://github.com/trzsz/trzsz#trouble-shooting 中文：https://trzsz.github.io/cn/
> 
> 另外，也可以用 [tssh](https://github.com/trzsz/trzsz-ssh) 代替 `trzsz ssh`，速度会更快。

好的，感谢支持

**Comment by lonnywong** [comment]
> 顺带问一句如何上传的时候保证权限一致上传

@zkcrescent [go 版 trzsz](https://github.com/trzsz/trzsz-go) `v1.1.7` 支持保持权限一致了。
