### ISSUE TITLE
use tsz to download file, but no action in centos

### ISSUE THREAD

**Issue by wonb168** [trzsz/trzsz#48]
[root@lanzhong-qa tmp]# /opt/python3.11/bin/tsz stockorg_str_info.parquet 
::TRZSZ:TRANSFER:S:1.1.4:0470305161700

almost this, 
how to download file?

I use ssh to login a jumpserver,
and then /p, and choose 1 to a my target server，
and then run above command

**Comment by lonnywong** [comment]
You need to do some configuration on the client side: https://github.com/trzsz/trzsz#supported-terminals

Or use https://github.com/trzsz/trzsz-ssh to login to the jumpserver.

**Comment by wonb168** [comment]
I download trzsz-ssh, then still error:
[root@lanzhong-qa ~]# tsz /tmp/stockorg_str_info.parquet
Traceback (most recent call last):
  File "/opt/python3.11/lib/python3.11/site-packages/trzsz/svr/send.py", line 120, in main
    send_files(args, file_list)
  File "/opt/python3.11/lib/python3.11/site-packages/trzsz/svr/send.py", line 63, in send_files
    action = transfer.recv_action()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python3.11/lib/python3.11/site-packages/trzsz/libs/transfer.py", line 49, in recv_action
    action = utils.recv_json('ACT')
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python3.11/lib/python3.11/site-packages/trzsz/libs/utils.py", line 564, in recv_json
    dic = recv_string(typ, may_has_junk)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python3.11/lib/python3.11/site-packages/trzsz/libs/utils.py", line 479, in recv_string
    return decode_buffer(recv_check(typ, may_has_junk)).decode('utf8')
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python3.11/lib/python3.11/site-packages/trzsz/libs/utils.py", line 454, in recv_check
    raise TrzszError(buf, typ)
trzsz.libs.utils.TrzszError: exit status 255: Error: 发生错误

**Comment by lonnywong** [comment]
Do you login to jumpserver with `tssh xxx`?

The jumpserver may added some junk while transferring.

Try install https://github.com/trzsz/trzsz-go on the server, and use `/usr/bin/tsz` (depends on where you install the go version trzsz to).

**Comment by lonnywong** [comment]
And, try to change the file `/opt/python3.11/lib/python3.11/site-packages/trzsz/libs/transfer.py`, line 49.

Change
```py
action = utils.recv_json('ACT')
```
to
```py
action = utils.recv_json('ACT', True)
```

**Comment by lonnywong** [comment]
@wonb168 Does it work?

**Comment by lonnywong** [comment]
I assume it works. If not, you can reopen this issue.
