### ISSUE TITLE
trz 命令卡住, 没有弹窗让选择文件

### ISSUE THREAD

**Issue by Subfire** [trzsz/trzsz#49]
# trz .
::TRZSZ:TRANSFER:R:1.1.7:0537486460200:42805

在远程 Linux 上运行 trz 命令, 然后直接卡着不动了

**Comment by lonnywong** [comment]
客户端需要配置的，文档：[https://trzsz.github.io/cn/](https://trzsz.github.io/cn/)，你拉到 `支持的终端` 那里看。

你可以试试 [https://github.com/trzsz/trzsz-ssh](https://github.com/trzsz/trzsz-ssh)，`tssh xxx` 登录即可。

**Comment by lonnywong** [comment]
我想正确配置客户端就是没问题的。如果有问题，可以重新打开此 issue。
