### ISSUE TITLE
我已经更新到最新的版本还是不能正常使用，是我的配置有问题吗

### ISSUE THREAD

**Issue by MF-ReStart** [trzsz/trzsz#5]

**Comment by MF-ReStart** [comment]
![image](https://user-images.githubusercontent.com/50358485/147302793-45a8608b-452f-406c-8fff-f87fb8ef1dc6.png)
这是我的mac电脑安装的客户端

**Comment by MF-ReStart** [comment]
这是我的服务器配置
![image](https://user-images.githubusercontent.com/50358485/147302897-92367e92-9b61-4ee1-9aa5-fd7dbd900595.png)

**Comment by MF-ReStart** [comment]
我的iterm2的触发器配置
![image](https://user-images.githubusercontent.com/50358485/147302949-eb52f4d4-3eca-44df-b6f2-8cb8237b8046.png)

**Comment by MF-ReStart** [comment]
我的iterm2 的command连接命令，我使用了sshpass 然后在ssh 是再使用tmux，这是我的连接命令：/usr/local/bin/sshpass -p '0' ssh -p 22 -t root@10.10.110.31 "tmux attach -t first-session || tmux new -s first-session"  确保我每一次连接都连接到first-session这个tmux Window

**Comment by MF-ReStart** [comment]
在我使用tsz 命令时，还是发生了这样的问题
![image](https://user-images.githubusercontent.com/50358485/147303147-47b5ffe5-6c51-44f2-ba25-ae60e9663813.png)

**Comment by lonnywong** [comment]
在客户端输出的错误信息是怎么样的？或者没有输出，卡住了？

迟点我试试你这种使用方式，看能不能复现出来。

**Comment by lonnywong** [comment]
另外，建议 tmux 加上参数 -CC ，可以与 iTerm2 无缝集成，非常好用。网上有很多教程，可以搜一下，YouTube上也有视频。

**Comment by MF-ReStart** [comment]
使用 -CC 会打开两个窗口，我只需要使用一个窗口保存我的工作环境，我想每一次登录到我的服务器都是使用同一个first-session，我只需要一个窗口就够了，这样更简单

**Comment by MF-ReStart** [comment]
我要怎么做才能实现呢

**Comment by lonnywong** [comment]
> 使用 -CC 会打开两个窗口，我只需要使用一个窗口保存我的工作环境，我想每一次登录到我的服务器都是使用同一个first-session，我只需要一个窗口就够了，这样更简单

可以只用一个窗口的，并且每次登录都能使用那个 session。
```
/usr/local/bin/sshpass -p '0' ssh -p 22 -t root@10.10.110.31 "tmux -CC attach -t first-session || tmux -CC new -s first-session" 
```
如果 iTerm2 不报错的就可以了，如果报错可能要设置一下服务器的字符集。
更多高级功能，可以看网上的教程。

**Comment by lonnywong** [comment]
另外，建议用 ssh 私钥免密登录，sshpass 这种使用明文密码的方式不太安全。
具体做法网上搜一下，也有很多教程。

**Comment by lonnywong** [comment]
> 我不需要使用-CC参数，我只需要iterm打开一个窗口来控制所有的服务器标签页就可以了，现在不能使用不是-CC
> 参数的问题，iterm2也没有报日志的错误，不知道我是不是把错误关闭了，现在看不到错误日志

-CC 只是一个建议，好像 iTerm2 会默认显示 2 个窗口，可以设置一下，就只显示一个窗口了。迟点我补个配置的截图上来。

不用 -CC 不能用的问题，我迟点看一下，到时可能需要你配合看一下是什么样的环境问题。

**Comment by MF-ReStart** [comment]
好的，你有时间的话，我这个环境会为你保留

**Comment by lonnywong** [comment]
> 

我的配置，供参考：

![image](https://user-images.githubusercontent.com/20320324/147307425-70ba8132-3f61-4310-aa61-12a425bfc88a.png)

**Comment by lonnywong** [comment]
我大概知道了，估计是 tmux 版本的问题，我测试时用的 tmux 是 2.1 的，我刚试了一下 1.8 的 tmux 是有问题。

原来 1.8 的 tmux 还不支持 #{client_control_mode} ，导致判断是否 -CC 控制模式时误判了。我来兼容一下。

查看 tmux 版本的方法：
```
tmux -V
```

**Comment by MF-ReStart** [comment]
我客户端的tmux版本是3.2a，服务器的tmux版本是tmux 3.0a

**Comment by MF-ReStart** [comment]
我什么时候能再测试trzsz呢，我到现在还没有成功使用过，我迫不及待了，谢谢你

**Comment by lonnywong** [comment]
> 我什么时候能再测试trzsz呢，我到现在还没有成功使用过，我迫不及待了，谢谢你

可以先试试测试版，只要服务端更新即可，客户端可以继续用 v0.1.4。

1. 卸载服务端 v0.1.4
```
sudo python3 -m pip uninstall trzsz-libs trzsz-svr
```
2. 安装服务端测试版 v0.2.30
```
sudo python3 -m pip install --upgrade -i https://test.pypi.org/simple/ trzsz-svr==0.2.30
```

等发布 v0.1.5 之后，安装回正式版本：
1. 卸载服务端测试版
```
sudo python3 -m pip uninstall trzsz-libs trzsz-svr
```
2. 安装服务端正式版
```
sudo python3 -m pip install --upgrade trzsz-libs trzsz-svr
```

**Comment by lonnywong** [comment]
> 我什么时候能再测试trzsz呢，我到现在还没有成功使用过，我迫不及待了，谢谢你

稍等，v0.2.30 的测试版还是有点问题。

你的用法是给 tmux session 起名为 first-session 了，我先研究下这种情况下如何判断是否为控制模式。

**Comment by MF-ReStart** [comment]
对的，我不习惯使用-CC，因为-CC是在正常连接的基础上再进入tmux，按照你的配置即使是在同一个窗口下我也不习惯，正常ssh连接和tmux Window这两个会让我感到困惑，我喜欢简单的，就在一个标签页实现tmux和lrzsz的功能，而且这个session只有我一个人使用，我会感到很舒服

**Comment by MF-ReStart** [comment]
![image](https://user-images.githubusercontent.com/50358485/147324317-5f8c6055-0e21-4a15-9aff-4e9fdc4d62d8.png)
zh这么多年过去了，这个问题还是没有得到解决，希望你的trzsz是一个伟大的开始，谢谢你的付出

**Comment by lonnywong** [comment]
来试试 https://github.com/trzsz/trzsz/issues/5#issuecomment-1000661064 这个测试版本 v0.2.31，这次应该可以了。

**Comment by lonnywong** [comment]
感谢你的反馈，让我了解到在不同使用场景下可能会遇到的问题。

**Comment by MF-ReStart** [comment]
你好，我刚才测试了v0.2.30版本，我能够成功上传下载了，这让我非常激动。但是没有进度条显示，而且能把按任意键继续取消掉吗

**Comment by MF-ReStart** [comment]
还有一个问题，每次上传和下载都好像进入一个新的页面，能够在原来的页面下显示上传下载吗，就像rz sz一样，你认为这样是不是更好呢，进入一个新的页面在上传下载文件时我会看不到我之前的路径和操作，我会不安心
![image](https://user-images.githubusercontent.com/50358485/147330638-d430f4a0-fb98-486d-9060-8b9411ce9e91.png)

**Comment by lonnywong** [comment]
> 你好，我刚才测试了v0.2.30版本，我能够成功上传下载了，这让我非常激动。但是没有进度条显示，而且能把按任意键继续取消掉吗

没有显示进度条，可能是文件太小了（很快就传完了），也可能是没有正确安装`zenity`，试试下面这个输出什么？
```
/usr/local/bin/zenity -version
```

按任意键取消这个，如果不显示，就看不到结果了。这跟另外开一个 tmux window 也有关系。

如果不开一个新的 tmux window 会有一些问题，tmux 老是输出一些垃圾信息，之前没有解决。

我周末再抽空看看有没有办法在原来的窗口进行传输。

**Comment by MF-ReStart** [comment]
![image](https://user-images.githubusercontent.com/50358485/147331617-1f4d529c-26c6-44a3-a0da-b493318d1db1.png)
这是我mac安装的版本

**Comment by lonnywong** [comment]
传个大点的文件试试？

**Comment by lonnywong** [comment]
> 你好，我刚才测试了v0.2.30版本，我能够成功上传下载了，这让我非常激动。但是没有进度条显示，而且能把按任意键继续取消掉吗

试试执行这个，看看有没有窗口弹出来：

```
/usr/local/bin/zenity --progress --title test --text uploading
```

**Comment by MF-ReStart** [comment]
我在传输大文件时可以看到进度条了，希望你能把上传下载文件在一个窗口下这个功能实现，谢谢你

**Comment by MF-ReStart** [comment]
周末愉快！希望你能继续开发trzsz，我期待trzsz变得更好

**Comment by MF-ReStart** [comment]
我发现文件传输的进度条在我鼠标点击回iterm2软件时，它会被隐藏到iterm2后面，你觉得需要在文件传输时固定进度条，禁止点击iterm2吗，我这个只是建议，具体看你觉得怎么样更好呢

**Comment by lonnywong** [comment]
> 我在传输大文件时可以看到进度条了，希望你能把上传下载文件在一个窗口下这个功能实现，谢谢你

想到一个巧妙的解决办法，今晚应该就能实现。Linux 真是妙啊！

**Comment by MF-ReStart** [comment]
> > 我在传输大文件时可以看到进度条了，希望你能把上传下载文件在一个窗口下这个功能实现，谢谢你
> 
> 想到一个巧妙的解决办法，今晚应该就能实现。Linux 真是妙啊！

我非常期待啊，加油！

**Comment by lonnywong** [comment]
> 我发现文件传输的进度条在我鼠标点击回iterm2软件时，它会被隐藏到iterm2后面，你觉得需要在文件传输时固定进度条，禁止点击iterm2吗，我这个只是建议，具体看你觉得怎么样更好呢

macOS 不支持，这个暂时只能这样啦。

**Comment by MF-ReStart** [comment]
> > 我发现文件传输的进度条在我鼠标点击回iterm2软件时，它会被隐藏到iterm2后面，你觉得需要在文件传输时固定进度条，禁止点击iterm2吗，我这个只是建议，具体看你觉得怎么样更好呢
> 
> macOS 不支持，这个暂时只能这样啦。

好吧，这个问题也不影响。 我能向你提个问题吗？关于tmux的，我的tmux不知道是不是配置不正确，我使用时经常会遇到这个问题，你知道可能会是什么原因造成的吗？我已经在tmux反馈了，https://github.com/tmux/tmux/issues/3016
你有时间能看看吗，或许你知道答案，谢谢

**Comment by lonnywong** [comment]
> > > 我发现文件传输的进度条在我鼠标点击回iterm2软件时，它会被隐藏到iterm2后面，你觉得需要在文件传输时固定进度条，禁止点击iterm2吗，我这个只是建议，具体看你觉得怎么样更好呢
> > 
> > 
> > macOS 不支持，这个暂时只能这样啦。
> 
> 好吧，这个问题也不影响。 我能向你提个问题吗？关于tmux的，我的tmux不知道是不是配置不正确，我使用时经常会遇到这个问题，你知道可能会是什么原因造成的吗？我已经在tmux反馈了，[tmux/tmux#3016](https://github.com/tmux/tmux/issues/3016) 你有时间能看看吗，或许你知道答案，谢谢

可能与 `history-limit` 有关 https://stackoverflow.com/questions/18760281/how-to-increase-scrollback-buffer-size-in-tmux

**Comment by MF-ReStart** [comment]
> > > > 我发现文件传输的进度条在我鼠标点击回iterm2软件时，它会被隐藏到iterm2后面，你觉得需要在文件传输时固定进度条，禁止点击iterm2吗，我这个只是建议，具体看你觉得怎么样更好呢
> > > 
> > > 
> > > macOS 不支持，这个暂时只能这样啦。
> > 
> > 
> > 好吧，这个问题也不影响。 我能向你提个问题吗？关于tmux的，我的tmux不知道是不是配置不正确，我使用时经常会遇到这个问题，你知道可能会是什么原因造成的吗？我已经在tmux反馈了，[tmux/tmux#3016](https://github.com/tmux/tmux/issues/3016) 你有时间能看看吗，或许你知道答案，谢谢
> 
> 可能与 `history-limit` 有关 https://stackoverflow.com/questions/18760281/how-to-increase-scrollback-buffer-size-in-tmux

那么这个tmux的配置我应该是配置在我的mac客户端还是我的服务器上呢？

**Comment by lonnywong** [comment]
> > > > > 我发现文件传输的进度条在我鼠标点击回iterm2软件时，它会被隐藏到iterm2后面，你觉得需要在文件传输时固定进度条，禁止点击iterm2吗，我这个只是建议，具体看你觉得怎么样更好呢
> > > > 
> > > > 
> > > > macOS 不支持，这个暂时只能这样啦。
> > > 
> > > 
> > > 好吧，这个问题也不影响。 我能向你提个问题吗？关于tmux的，我的tmux不知道是不是配置不正确，我使用时经常会遇到这个问题，你知道可能会是什么原因造成的吗？我已经在tmux反馈了，[tmux/tmux#3016](https://github.com/tmux/tmux/issues/3016) 你有时间能看看吗，或许你知道答案，谢谢
> > 
> > 
> > 可能与 `history-limit` 有关 https://stackoverflow.com/questions/18760281/how-to-increase-scrollback-buffer-size-in-tmux
> 
> 那么这个tmux的配置我应该是配置在我的mac客户端还是我的服务器上呢？

在服务器上。mac上不用安装 tmux 的。

**Comment by MF-ReStart** [comment]
哦，这样啊，我试试，谢谢你

**Comment by MF-ReStart** [comment]
> 哦，这样啊，我试试，谢谢你



> > > > > > 我发现文件传输的进度条在我鼠标点击回iterm2软件时，它会被隐藏到iterm2后面，你觉得需要在文件传输时固定进度条，禁止点击iterm2吗，我这个只是建议，具体看你觉得怎么样更好呢
> > > > > 
> > > > > 
> > > > > macOS 不支持，这个暂时只能这样啦。
> > > > 
> > > > 
> > > > 好吧，这个问题也不影响。 我能向你提个问题吗？关于tmux的，我的tmux不知道是不是配置不正确，我使用时经常会遇到这个问题，你知道可能会是什么原因造成的吗？我已经在tmux反馈了，[tmux/tmux#3016](https://github.com/tmux/tmux/issues/3016) 你有时间能看看吗，或许你知道答案，谢谢
> > > 
> > > 
> > > 可能与 `history-limit` 有关 https://stackoverflow.com/questions/18760281/how-to-increase-scrollback-buffer-size-in-tmux
> > 
> > 
> > 那么这个tmux的配置我应该是配置在我的mac客户端还是我的服务器上呢？
> 
> 在服务器上。mac上不用安装 tmux 的。

哦，这样啊，我试试，谢谢你

**Comment by lonnywong** [comment]
> 我非常期待啊，加油！

试试 v0.2.33 https://github.com/trzsz/trzsz/issues/5#issuecomment-1000661064 ，不用再新开一个 tmux window 了。

**Comment by MF-ReStart** [comment]
> > 哦，这样啊，我试试，谢谢你
> 
> > > > > > > 我发现文件传输的进度条在我鼠标点击回iterm2软件时，它会被隐藏到iterm2后面，你觉得需要在文件传输时固定进度条，禁止点击iterm2吗，我这个只是建议，具体看你觉得怎么样更好呢
> > > > > > 
> > > > > > 
> > > > > > macOS 不支持，这个暂时只能这样啦。
> > > > > 
> > > > > 
> > > > > 好吧，这个问题也不影响。 我能向你提个问题吗？关于tmux的，我的tmux不知道是不是配置不正确，我使用时经常会遇到这个问题，你知道可能会是什么原因造成的吗？我已经在tmux反馈了，[tmux/tmux#3016](https://github.com/tmux/tmux/issues/3016) 你有时间能看看吗，或许你知道答案，谢谢
> > > > 
> > > > 
> > > > 可能与 `history-limit` 有关 https://stackoverflow.com/questions/18760281/how-to-increase-scrollback-buffer-size-in-tmux
> > > 
> > > 
> > > 那么这个tmux的配置我应该是配置在我的mac客户端还是我的服务器上呢？
> > 
> > 
> > 在服务器上。mac上不用安装 tmux 的。
> 
> 哦，这样啊，我试试，谢谢你

我配置了，但是还是存在这个问题，我很沮丧，不能正确查看到文件的内容，我使用tmux的意义都不存在了，请问你在使用tmux时没有遇到过这个问题吗，显示几千甚至上万行的文件内容时，你的tmux能正常显示吗

**Comment by MF-ReStart** [comment]
> > 我非常期待啊，加油！
> 
> 试试 v0.2.33 [#5 (comment)](https://github.com/trzsz/trzsz/issues/5#issuecomment-1000661064) ，不用再新开一个 tmux window 了。

我测试了，非常酷啊

**Comment by lonnywong** [comment]
> > > 我非常期待啊，加油！
> > 
> > 
> > 试试 v0.2.33 [#5 (comment)](https://github.com/trzsz/trzsz/issues/5#issuecomment-1000661064) ，不用再新开一个 tmux window 了。
> 
> 我测试了，非常酷啊

谢谢你的参与。

**Comment by lonnywong** [comment]
v0.1.5 已发布

**Comment by boomker** [comment]
> v0.1.5 已发布

新版似乎还是有些问题，  我遇到了和  @MF-ReStart 同样的情况，报错日志：

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/trzsz/iterm2/main.py", line 180, in main

    upload_files()

  File "/usr/local/lib/python3.9/site-packages/trzsz/iterm2/main.py", line 165, in upload_files

    remote_list = send_files(file_list, callback)

  File "/usr/local/lib/python3.9/site-packages/trzsz/libs/utils.py", line 233, in send_files

    check_succ()

  File "/usr/local/lib/python3.9/site-packages/trzsz/libs/utils.py", line 126, in check_succ

    raise TrzszError(buf, typ)

trzsz.libs.utils.TrzszError: [TrzszError] P=1s\[1;42r[42;169H

![image](https://user-images.githubusercontent.com/19751472/147378739-046b844f-f04d-4c06-8c0e-4f21dac35e2c.png)

**Comment by lonnywong** [comment]
> > v0.1.5 已发布
> 
> 新版似乎还是有些问题， 我遇到了和 @MF-ReStart 同样的情况，报错日志：

在你执行 `trz` 的那个环境，执行 `tmux display-message -p '#{client_tty}:#{client_control_mode}'` 看看输出什么？

**Comment by lonnywong** [comment]
> > v0.1.5 已发布
> 
> 新版似乎还是有些问题， 我遇到了和 @MF-ReStart 同样的情况，报错日志：

@boomker 是否在文件传输过程中做了什么操作？

现在不能从机制上防止用户在传输过程中按键盘，只要按键盘就会发送一些字符到服务器，也可能会让服务器产生一些输出，这会影响到文件传输，导致报错。

**Comment by boomker** [comment]
> 

![image](https://user-images.githubusercontent.com/19751472/147400892-705bc0de-6cf4-4989-97f0-4485c4ebfe3d.png)

**Comment by boomker** [comment]
> > > v0.1.5 已发布
> > 
> > 
> > 新版似乎还是有些问题， 我遇到了和 @MF-ReStart 同样的情况，报错日志：
> 
> @boomker 是否在文件传输过程中做了什么操作？
> 
> 现在不能从机制上防止用户在传输过程中按键盘，只要按键盘就会发送一些字符到服务器，也可能会让服务器产生一些输出，这会影响到文件传输，导致报错。

传输文件过程中，没有进行任何操作， 没有碰键盘。 问题现象： 文件上传到 服务器过程中， iterm2 会报错， 查看文件大小不一致

**Comment by lonnywong** [comment]
> 传输文件过程中，没有进行任何操作， 没有碰键盘。 问题现象： 文件上传到 服务器过程中， iterm2 会报错， 查看文件大小不一致. 发现上传 小文件不会有问题

在服务端再看看 `tmux -V` 是什么版本？

有没有将 tmux 窗口分成多个？如果分隔成多个小窗口，在传输文件过程中，另外的小窗口有没有在输出？ 

另外，你是用什么样的命令进入 tmux 的？tmux 有没有什么特殊的配置？

**Comment by lonnywong** [comment]
> ![image](https://user-images.githubusercontent.com/19751472/147400892-705bc0de-6cf4-4989-97f0-4485c4ebfe3d.png)

看你这截图，难道你是在 mac 上运行 tmux ，然后分成两个窗口，下面这个窗口再 ssh 到远程服务器？

一般都是先 ssh 到远程服务上，在远程服务器上再运行 tmux 的；下次 ssh 到远程服务器上，就 attach 到原来运行的 tmux session。这样即使网络断开了，在服务器上运行的程序也不会停止。

你的这种用法是有什么特殊目的吗？

**Comment by boomker** [comment]
> > ![image](https://user-images.githubusercontent.com/19751472/147400892-705bc0de-6cf4-4989-97f0-4485c4ebfe3d.png)
> 
> 看你这截图，难道你是在 mac 上运行 tmux ，然后分成两个窗口，下面这个窗口再 ssh 到远程服务器？
> 
> 一般都是先 ssh 到远程服务上，在远程服务器上再运行 tmux 的；下次 ssh 到远程服务器上，就 attach 到原来运行的 tmux session。这样即使网络断开了，在服务器上运行的程序也不会停止。
> 
> 你的这种用法是有什么特殊目的吗？

我的使用场景： 

     本地需要远程到不同的机器，远程机器互相之间不一定都互通的。 另外远程机器也不一定允许安装 tmux  (生产环境服务器)
     
     Mac 本地开 tmux， 主要是可以开多个 pane，在各个 pane 上处理不同的任务，有时候 pane 里滚动的日志需要快捷导出到本地。

**Comment by boomker** [comment]
> > 传输文件过程中，没有进行任何操作， 没有碰键盘。 问题现象： 文件上传到 服务器过程中， iterm2 会报错， 查看文件大小不一致. 发现上传 小文件不会有问题
> 
> 在服务端再看看 `tmux -V` 是什么版本？
> 
> 有没有将 tmux 窗口分成多个？如果分隔成多个小窗口，在传输文件过程中，另外的小窗口有没有在输出？
> 
> 另外，你是用什么样的命令进入 tmux 的？tmux 有没有什么特殊的配置？

我的情况：
    tmux 版本：3.2a,  本地开tmux， tmux 开了多个窗口，其他窗口没有输出
    
    进入 tmux 命令： tmux 或者 tmux attach -t  $sessionID

**Comment by lonnywong** [comment]
> 进入 tmux 命令： tmux 或者 tmux attach -t  $sessionID

你可以这样用 `tmux -CC` 或者 `tmux -CC attach -t  $sessionID`，就是在你原来的基础上增加 `-CC`，然后 trzsz 就正常了。

iTerm2 在默认情况下，`tmux -CC`会有两个窗口，你可以像这样 https://github.com/trzsz/trzsz/issues/5#issuecomment-1000611023 设置，就只有一个窗口了。

`Command + d` 左右分屏，`Command + Shift + D` 上下分屏。

iTerm2 在默认情况下，`tmux -CC`分屏时上面显示状态条挺丑的，可以设置不显示：

<img width="776" alt="Screen Shot 2021-12-26 at 7 08 45 PM" src="https://user-images.githubusercontent.com/20320324/147406242-52fa5b31-a6ba-4b0d-bbc9-8dc952f407fd.png">

**Comment by MF-ReStart** [comment]
> > > > 我发现文件传输的进度条在我鼠标点击回iterm2软件时，它会被隐藏到iterm2后面，你觉得需要在文件传输时固定进度条，禁止点击iterm2吗，我这个只是建议，具体看你觉得怎么样更好呢
> > > 
> > > 
> > > macOS 不支持，这个暂时只能这样啦。
> > 
> > 
> > 好吧，这个问题也不影响。 我能向你提个问题吗？关于tmux的，我的tmux不知道是不是配置不正确，我使用时经常会遇到这个问题，你知道可能会是什么原因造成的吗？我已经在tmux反馈了，[tmux/tmux#3016](https://github.com/tmux/tmux/issues/3016) 你有时间能看看吗，或许你知道答案，谢谢
> 
> 可能与 `history-limit` 有关 https://stackoverflow.com/questions/18760281/how-to-increase-scrollback-buffer-size-in-tmux

我在tmux提的issues得到的答复是：
tmux并不试图保持终端回滚的一致性，如果输出不会影响可见窗格，那么它不一定会被发送到终端。你将需要使用复制模式或使用iTerm2的tmux集成。

我在网上搜索了一下，大概是tmux维护着自己的回滚缓冲区这与系统的回滚缓冲区不一样，而且在复制模式中复制的内容，无法共享到系统剪贴板，这非常不方便。使用了tmux之后在终端上回滚看到的内容不一定就是100%正确的内容，tmux只确保自己的回滚缓冲区是正确的，我看github也有对这个问题的项目，但是我配置之后并不能正常生效，不知道什么原因，这是github的项目地址https://github.com/gpakosz/.tmux

请问你平时使用tmux没有这些困扰吗，有时间一起讨论一下吗

**Comment by lonnywong** [comment]
> > > 好吧，这个问题也不影响。 我能向你提个问题吗？关于tmux的，我的tmux不知道是不是配置不正确，我使用时经常会遇到这个问题，你知道可能会是什么原因造成的吗？我已经在tmux反馈了，[tmux/tmux#3016](https://github.com/tmux/tmux/issues/3016) 你有时间能看看吗，或许你知道答案，谢谢
> > 
> > 
> > 可能与 `history-limit` 有关 https://stackoverflow.com/questions/18760281/how-to-increase-scrollback-buffer-size-in-tmux
> 
> 我在tmux提的issues得到的答复是： tmux并不试图保持终端回滚的一致性，如果输出不会影响可见窗格，那么它不一定会被发送到终端。你将需要使用复制模式或使用iTerm2的tmux集成。
> 
> 我在网上搜索了一下，大概是tmux维护着自己的回滚缓冲区这与系统的回滚缓冲区不一样，而且在复制模式中复制的内容，无法共享到系统剪贴板，这非常不方便。使用了tmux之后在终端上回滚看到的内容不一定就是100%正确的内容，tmux只确保自己的回滚缓冲区是正确的，我看github也有对这个问题的项目，但是我配置之后并不能正常生效，不知道什么原因，这是github的项目地址https://github.com/gpakosz/.tmux
> 
> 请问你平时使用tmux没有这些困扰吗，有时间一起讨论一下吗

我用的就是他们说的 [iTerm2's tmux integration](https://iterm2.com/documentation-tmux-integration.html)，也就是 tmux -CC 控制模式，与 iTerm2 无缝集成，非常的好用。

我的配置可以参考 https://github.com/trzsz/trzsz/issues/5#issuecomment-1001158370

**Comment by MF-ReStart** [comment]
> > > > 好吧，这个问题也不影响。 我能向你提个问题吗？关于tmux的，我的tmux不知道是不是配置不正确，我使用时经常会遇到这个问题，你知道可能会是什么原因造成的吗？我已经在tmux反馈了，[tmux/tmux#3016](https://github.com/tmux/tmux/issues/3016) 你有时间能看看吗，或许你知道答案，谢谢
> > > 
> > > 
> > > 可能与 `history-limit` 有关 https://stackoverflow.com/questions/18760281/how-to-increase-scrollback-buffer-size-in-tmux
> > 
> > 
> > 我在tmux提的issues得到的答复是： tmux并不试图保持终端回滚的一致性，如果输出不会影响可见窗格，那么它不一定会被发送到终端。你将需要使用复制模式或使用iTerm2的tmux集成。
> > 我在网上搜索了一下，大概是tmux维护着自己的回滚缓冲区这与系统的回滚缓冲区不一样，而且在复制模式中复制的内容，无法共享到系统剪贴板，这非常不方便。使用了tmux之后在终端上回滚看到的内容不一定就是100%正确的内容，tmux只确保自己的回滚缓冲区是正确的，我看github也有对这个问题的项目，但是我配置之后并不能正常生效，不知道什么原因，这是github的项目地址https://github.com/gpakosz/.tmux
> > 请问你平时使用tmux没有这些困扰吗，有时间一起讨论一下吗
> 
> 我用的就是他们说的 [iTerm2's tmux integration](https://iterm2.com/documentation-tmux-integration.html)，也就是 tmux -CC 控制模式，与 iTerm2 无缝集成，非常的好用。
> 
> 我的配置可以参考 [#5 (comment)](https://github.com/trzsz/trzsz/issues/5#issuecomment-1001158370)
我现在使用-CC参数也是存在一样的问题，我在iterm2上进入服务器在进入tmux的，我的command是：ssh -p '2222' 'root@10.10.110.31' -t "tmux -CC attach -t first-session || tmux new -s first-session"

我可以把文件发给你，然后你cat 下，看看你的是不是能够完整显示文件内容呢？

**Comment by MF-ReStart** [comment]
> > > > > 好吧，这个问题也不影响。 我能向你提个问题吗？关于tmux的，我的tmux不知道是不是配置不正确，我使用时经常会遇到这个问题，你知道可能会是什么原因造成的吗？我已经在tmux反馈了，[tmux/tmux#3016](https://github.com/tmux/tmux/issues/3016) 你有时间能看看吗，或许你知道答案，谢谢
> > > > 
> > > > 
> > > > 可能与 `history-limit` 有关 https://stackoverflow.com/questions/18760281/how-to-increase-scrollback-buffer-size-in-tmux
> > > 
> > > 
> > > 我在tmux提的issues得到的答复是： tmux并不试图保持终端回滚的一致性，如果输出不会影响可见窗格，那么它不一定会被发送到终端。你将需要使用复制模式或使用iTerm2的tmux集成。
> > > 我在网上搜索了一下，大概是tmux维护着自己的回滚缓冲区这与系统的回滚缓冲区不一样，而且在复制模式中复制的内容，无法共享到系统剪贴板，这非常不方便。使用了tmux之后在终端上回滚看到的内容不一定就是100%正确的内容，tmux只确保自己的回滚缓冲区是正确的，我看github也有对这个问题的项目，但是我配置之后并不能正常生效，不知道什么原因，这是github的项目地址https://github.com/gpakosz/.tmux
> > > 请问你平时使用tmux没有这些困扰吗，有时间一起讨论一下吗
> > 
> > 
> > 我用的就是他们说的 [iTerm2's tmux integration](https://iterm2.com/documentation-tmux-integration.html)，也就是 tmux -CC 控制模式，与 iTerm2 无缝集成，非常的好用。
> > 我的配置可以参考 [#5 (comment)](https://github.com/trzsz/trzsz/issues/5#issuecomment-1001158370)
> 
> 我现在使用-CC参数也是存在一样的问题，我在iterm2上进入服务器在进入tmux的，我的command是：ssh -p '2222' 'root@10.10.110.31' -t "tmux -CC attach -t first-session || tmux new -s first-session"
> 
> 我可以把文件发给你，然后你cat 下，看看你的是不是能够完整显示文件内容呢？
文件你可以在这个链接得到https://hercules-gitbook-image.oss-cn-shenzhen.aliyuncs.com/bug/test.conf

**Comment by lonnywong** [comment]
> 我可以把文件发给你，然后你cat 下，看看你的是不是能够完整显示文件内容呢？ 文件你可以在这个链接得到https://hercules-gitbook-image.oss-cn-shenzhen.aliyuncs.com/bug/test.conf

我这里没有问题。

`tmux -CC attach -t first-session || tmux -CC new -s first-session` 注意后面也要加 `-CC`

另外，这里要配置一下：

![image](https://user-images.githubusercontent.com/20320324/147465049-49066f0d-761c-4bfb-8372-717aba10789f.png)

还有，我在 `~/.tmux.conf` 中还配置了 `set-option -g history-limit 1000000`，不过这应该不影响。

**Comment by MF-ReStart** [comment]
> > 我可以把文件发给你，然后你cat 下，看看你的是不是能够完整显示文件内容呢？ 文件你可以在这个链接得到https://hercules-gitbook-image.oss-cn-shenzhen.aliyuncs.com/bug/test.conf
> 
> 我这里没有问题。
> 
> `tmux -CC attach -t first-session || tmux -CC new -s first-session` 注意后面也要加 `-CC`
> 
> 另外，这里要配置一下：
> 
> ![image](https://user-images.githubusercontent.com/20320324/147465049-49066f0d-761c-4bfb-8372-717aba10789f.png)
> 
> 还有，我在 `~/.tmux.conf` 中还配置了 `set-option -g history-limit 1000000`，不过这应该不影响。
> 
> 最后补充一下，快捷键 `fn + command + <-` 和 `fn + command + ->` 快速滚到最上面、最下面。 （`<-` 指向左箭头键，`->` 指向右箭头键）

是我后面没有加-CC的问题，现在可以正常查看终端的回滚了，但是现在我如果直接点左上角的叉把这个窗口关掉，我下次连接进来时会弹这个窗口
![image](https://user-images.githubusercontent.com/50358485/147466267-90092cfa-590e-4f12-a15b-29bbf3635ffb.png)

还有就是我的标签页的名字也变了，本来是ip地址的
![image](https://user-images.githubusercontent.com/50358485/147466388-98e8fd1c-af00-4026-b46a-e1873d6359ff.png)

你每次重新连接都要手动去点这个吗
![image](https://user-images.githubusercontent.com/50358485/147466455-90f14b8e-c271-4bd6-adbe-bb65d02aa2bb.png)

你是怎么完全退出或者保持分离tmux的？

**Comment by lonnywong** [comment]
我是这样使用的 `ssh xxx -t 'tmux -CC new-session -A -s xxx /bin/bash'`，`control + command + shift + d` 分离，下次也是使用同样的命令，没有你这样的提示。

在 `.bashrc` 或者其他会自动执行的脚本中添加 `export PROMPT_COMMAND="echo -ne \"\\033]0;abcd\\007\""`，窗口名字就会改成 `abcd`，根据你的需要改一下就好了。

另外要注意的就是这里的配置 https://github.com/trzsz/trzsz/issues/5#issuecomment-1000611023

**Comment by lonnywong** [comment]
> 你每次重新连接都要手动去点这个吗 ![image](https://user-images.githubusercontent.com/50358485/147466455-90f14b8e-c271-4bd6-adbe-bb65d02aa2bb.png)

下面不是有个勾吗？你把这个勾取消掉就可以了吧。

**Comment by MF-ReStart** [comment]
> ssh xxx -t 'tmux -CC new-session -A -s xxx /bin/bash'

请问-A和-s参数是什么作用？还有xxx是代表的什么呢

**Comment by lonnywong** [comment]
前面的 `xxx` 是在 `.ssh/config` 里配置的名字，后面的 `-s xxx` 是给 tmux session 起的名字。
`-A` 是如果存在同名的 session 就 attach 上去，不存在就新建一个。

**Comment by MF-ReStart** [comment]
可以了，非常感谢你！！！
记录一下这个是iterm2的tmux集成最佳实践https://gitlab.com/gnachman/iterm2/-/wikis/tmux-Integration-Best-Practices
