### ISSUE TITLE
设置-t参数仍然报错

### ISSUE THREAD

**Issue by ChristmasZCY** [trzsz/trzsz#50]
您好，我在下载文件时使用`tsz -y -t -1 func.tgz` 在下载一段时间过后仍然会导致错误退出，请问是什么原因呢，如图
<img width="1328" alt="image" src="https://github.com/trzsz/trzsz/assets/61818189/0fbf394c-43fc-484f-b677-2506d43e79ed">

**Comment by lonnywong** [comment]
可能是你那个有颜色的 shell 每过一段时间会输出一些东西，影响了 tsz 传文件。

1、升级到最新版本的 trzsz 试试看。

2、如果你是直连服务器，没有经过跳板机之类的，可以试试 go 版的 trzsz 和 tssh，这两个组合会优先走 ssh 隧道，没那么容易受 shell 的非预期输出影响。
https://github.com/trzsz/trzsz-go
https://github.com/trzsz/trzsz-ssh

**Comment by ChristmasZCY** [comment]
原来是这样 ，我找到了iTerm设置中的如图所示，尝试几次发现报错没有再出现。多谢～
<img width="609" alt="image" src="https://github.com/trzsz/trzsz/assets/61818189/5a015e46-ff8e-463b-82fe-bce1f5aa5236">

**Comment by lonnywong** [comment]
发送 0 ？`v1.1.5` 会把 0 去掉： https://github.com/trzsz/trzsz/blob/3ebf4e62be1b5b99e51e03ade5fc26c7ea85cba2/trzsz-libs/trzsz/libs/utils.py#L443

你可以升级试一下，客户端和服务端都升级。

**Comment by ChristmasZCY** [comment]
我原来客户端的版本是`1.1.4`，服务端是`1.1.0`，都切换为`1.1.5`后，打开上图的设置也不会出现`trzsz.libs.utils.TrzszError: [TrzszError] #SUCC: 2097152`了，非常感谢！
