### ISSUE TITLE
trzsz tmux is frozen in trz file process

### ISSUE THREAD

**Issue by sunzhusz** [trzsz/trzsz#52]
when i trz file in tmux split pane, the whole window is frozen

**Comment by lonnywong** [comment]
trzsz uses stdin and stdout to transfer files, causing tmux to temporarily freeze as expected.

In the future, [trzsz-ssh ( tssh )](https://github.com/trzsz/trzsz-ssh) can consider supporting background file transfer via ssh tunnels, which may solve the issue.

**Comment by sunzhusz** [comment]
ok, i am waiting the feature. It is recommended to use a specific suffix or hidden file during the file transfer process, and change the file name to the original file name after the transfer is completed. This can prevent the transfer from failing or the file being removed during the transfer.

**Comment by lonnywong** [comment]
The latest [trzsz-go](https://github.com/trzsz/trzsz-go) and [trzsz-ssh](https://github.com/trzsz/trzsz-ssh) already support background transfer.

Before `trzsz-go 1.1.8` is released, you can install it on the server as follows:
```sh
go install github.com/trzsz/trzsz-go/cmd/...@latest
```

Before `trzsz-ssh 0.1.22` is released, you can install it on your local computer as follows:
```sh
go install github.com/trzsz/trzsz-ssh/cmd/tssh@latest
```

Then, use `~/go/bin/tssh xxx` to log in to the server, use `~/go/bin/trz -f` to upload in the background, and use `~/go/bin/tsz -f xxx` to download in the background.

Note that it does not support jump servers in the middle, unless you use ProxyJump to log in to the target server directly.
