### ISSUE TITLE
Any chance this could be made compatible with lrzsz ?

### ISSUE THREAD

**Issue by gitcnd** [trzsz/trzsz#54]
Right now, it doesn't support terminals like SecureCRT or interoperability with the real "sz" and "rz" options :-(

**Comment by lonnywong** [comment]
I made trzsz to be compatible with tmux. It is a completely different protocol from lrzsz, so it is not compatible with rz sz.

But, trzsz supports terminals with local shell, such as Windows Terminal, which can be used with [tssh](https://github.com/trzsz/trzsz-ssh).

**Comment by gitcnd** [comment]
tssh - Clever idea!

... unfortunately, my use case is upload/download to micropython MCU's over serial or telnet - so not tssh available :-(

**Comment by lonnywong** [comment]
> ... unfortunately, my use case is upload/download to micropython MCU's over serial or telnet - so not tssh available :-(

Install [trzsz-go](https://github.com/trzsz/trzsz-go) on local computer, and use `trzsz telnet x.x.x.x xx` to log in. Then trz tsz should work.
