### ISSUE TITLE
How to install on FreeBSD System?

### ISSUE THREAD

**Issue by licoba** [trzsz/trzsz#55]
I didn't find the tutorial

**Comment by lonnywong** [comment]
If you want to install the Python version, just `sudo python3 -m pip install --upgrade trzsz` on the server.

If you want to install the [Go version](https://github.com/trzsz/trzsz-go) (Recommended), just `go install github.com/trzsz/trzsz-go/cmd/...@latest` on the server.

**Comment by licoba** [comment]
OK, thank you. My server does not have a Go environment. It seems that I can only install the python version. Do I need to configure environment variables after installation? Or can I use it directly after installing it with python?

**Comment by lonnywong** [comment]
I will compile the freebsd binary in the next Go version. You can download and unzip it from [Go Releases](https://github.com/trzsz/trzsz-go/releases) to use.

**Comment by lonnywong** [comment]
> Do I need to configure environment variables after installation? Or can I use it directly after installing it with python?


As long as you can find `trz` and `tsz` after installation and run them.

**Comment by licoba** [comment]
Okay, thank you very much.
