### ISSUE TITLE
mac m1安装失败

### ISSUE THREAD

**Issue by awklinux** [trzsz/trzsz#6]
brew install ncruces/tap/zenity
Updating Homebrew...
Warning: You are using macOS 12.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
pre-release version.

==> Installing zenity from ncruces/tap
==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/bottles/go-1.16.5.arm64_big_sur.bottle.tar.gz
curl: (22) The requested URL returned error: 404

Warning: Bottle missing, falling back to the default domain...
==> Downloading https://ghcr.io/v2/homebrew/core/go/manifests/1.16.5
Already downloaded: /Users/kevin/Library/Caches/Homebrew/downloads/6cb2b73427bbc8aaa8c6e36b3ed5c1e05c36e2f7ff7dd024fe6823e4d21bb124--go-1.16.5.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/go/blobs/sha256:dde21eedfa67da23db70cf977ae82c0cadd5acf2a326cb91853ff54d0cf5886f
Already downloaded: /Users/kevin/Library/Caches/Homebrew/downloads/43084dae667d24344f85e66b006a6bdcd465a27844a1bb454ef15aaebb8d054f--go--1.16.5.arm64_big_sur.bottle.tar.gz
==> Downloading https://github.com/ncruces/zenity/archive/refs/tags/v0.7.12.tar.gz
Already downloaded: /Users/kevin/Library/Caches/Homebrew/downloads/d7901e2cde038f248801cd283ed6a60e843ed7af07fdb2ac7e83674b5a011657--zenity-0.7.12.tar.gz
==> Installing dependencies for ncruces/tap/zenity: go
==> Installing ncruces/tap/zenity dependency: go
==> Pouring go-1.16.5.arm64_big_sur.bottle.tar.gz
tar: Error opening archive: Failed to open '/Users/kevin/Library/Caches/Homebrew/downloads/63622908e08faac855f0fbc37ebb565ab403dc651f7587014e0d8727093e5d1c--go-1.16.5.arm64_big_sur.bottle.tar.gz'
Error: Failure while executing; `tar --extract --no-same-owner --file /Users/kevin/Library/Caches/Homebrew/downloads/63622908e08faac855f0fbc37ebb565ab403dc651f7587014e0d8727093e5d1c--go-1.16.5.arm64_big_sur.bottle.tar.gz --directory /private/tmp/d20211225-51941-1v4zqji` exited with 1. Here's the output:
tar: Error opening archive: Failed to open '/Users/kevin/Library/Caches/Homebrew/downloads/63622908e08faac855f0fbc37ebb565ab403dc651f7587014e0d8727093e5d1c--go-1.16.5.arm64_big_sur.bottle.tar.gz'

**Comment by lonnywong** [comment]
M1 ？看来是 zenity 目前未提供 arm 架构的安装包。

1. 可以去 https://github.com/ncruces/zenity 提个 issue
2. 或者试下用 go 编译的方式来安装（需要先安装go）
```
go get github.com/ncruces/zenity
```

**Comment by lonnywong** [comment]
试试这样安装行不行？
```
brew install go
go install 'github.com/ncruces/zenity/cmd/zenity@latest'
sudo cp ~/go/bin/zenity /usr/local/bin/zenity
```
