### ISSUE TITLE
有可能在termux中使用吗

### ISSUE THREAD

**Issue by LSQzzx** [trzsz/trzsz#61]
我安装了trzsz-go，并且使用root权限运行了trzsz ssh ****成功打开了ssh，在ssh中运行trz后提示本地Linux需要安装zenity

**Comment by lonnywong** [comment]
参考 https://github.com/trzsz/trzsz-go/issues/39#issuecomment-1728934126 ，可以网上搜搜 [Termux X11](https://github.com/termux/termux-x11) 的使用教程。

另外，推荐使用 tssh https://github.com/trzsz/trzsz-ssh/issues/121#issuecomment-2212313586
