### ISSUE TITLE
不能优雅取消

### ISSUE THREAD

**Issue by Ru-Xiang** [trzsz/trzsz#8]
上传过程中，ctr+c 无法取消上传。类似的，配置未完成情况下，也无法通过ctr+c退出

**Comment by lonnywong** [comment]
文档有写的，通过 ctrl + j 可以中断。这个快捷键之所以不是 ctrl + c，是与 linux 的 raw tty 有关，不是我想这样选的。





------------------ 原始邮件 ------------------
From: Ru Xiang ***@***.***&gt;
发送时间: 01/18/2022, 23:55
To: trzsz/trzsz ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
Subject: Re: [trzsz/trzsz] 不能优雅取消 (Issue #8)





 
上传过程中，ctr+c 无法取消上传。类似的，配置未完成情况下，也无法通过ctr+c退出
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lonnywong** [comment]
文档有写的，通过 ctrl + j 可以优雅退出的。

ctrl + j 实际会发送 \n 换行符，而 trzsz 的实现用了 python stdin 的 readline 函数，以 \n 换行符结束的，所以 ctrl + j 是可以优雅退出的。

如果是 `-b` 二进制模式，已经开始传输文件后，可能 ctrl + j 都不能优雅退出，因为二进制是可能包含 \n 换行符的。如果尝试 ctrl + j 后没有退出，可以等待 100 秒超时退出。

不建议直接 kill -9，那样没有机会还原 linux 的 tty ，可能需要重新登录才能正常使用了。
下个版本，我再加个 kill -15 或 kill -SIGTERM 还原 tty 的功能。

——————

刚突然想到，我为什么一定要用 readline 函数呢？自己写个类似的函数，那其实是有办法实现常用的 ctrl + c 退出的。下个版本加上 ctrl + c 优雅退出的功能。

**Comment by lonnywong** [comment]
[v0.3.1](https://github.com/trzsz/trzsz/releases/tag/v0.3.1) 已支持 `ctrl + c` 优雅退出。

升级和安装时的命令是一样的：

* 服务端
```
sudo python3 -m pip install --upgrade trzsz-libs trzsz-svr
```

* 客户端
```
sudo python3 -m pip install --upgrade trzsz-libs trzsz-iterm2
```
